/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ServiceResourcePolicy } from './service-resource-policy';

/**
 * 
 * @export
 * @interface IdmUserMetaNamespace
 */
export interface IdmUserMetaNamespace {
    /**
     * 
     * @type {boolean}
     * @memberof IdmUserMetaNamespace
     */
    'Indexable'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IdmUserMetaNamespace
     */
    'JsonDefinition'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdmUserMetaNamespace
     */
    'Label'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdmUserMetaNamespace
     */
    'Namespace'?: string;
    /**
     * 
     * @type {number}
     * @memberof IdmUserMetaNamespace
     */
    'Order'?: number;
    /**
     * 
     * @type {Array<ServiceResourcePolicy>}
     * @memberof IdmUserMetaNamespace
     */
    'Policies'?: Array<ServiceResourcePolicy>;
    /**
     * 
     * @type {boolean}
     * @memberof IdmUserMetaNamespace
     */
    'PoliciesContextEditable'?: boolean;
}

