/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ServiceResourcePolicyQuery } from './service-resource-policy-query';

/**
 * 
 * @export
 * @interface IdmSearchUserMetaRequest
 */
export interface IdmSearchUserMetaRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof IdmSearchUserMetaRequest
     */
    'MetaUuids'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof IdmSearchUserMetaRequest
     */
    'Namespace'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IdmSearchUserMetaRequest
     */
    'NodeUuids'?: Array<string>;
    /**
     * 
     * @type {ServiceResourcePolicyQuery}
     * @memberof IdmSearchUserMetaRequest
     */
    'ResourceQuery'?: ServiceResourcePolicyQuery;
    /**
     * 
     * @type {string}
     * @memberof IdmSearchUserMetaRequest
     */
    'ResourceSubjectOwner'?: string;
}

