/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobsTaskStatus } from './jobs-task-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RestNodeLocator } from './rest-node-locator';

/**
 * 
 * @export
 * @interface RestActionParameters
 */
export interface RestActionParameters {
    /**
     * 
     * @type {JobsTaskStatus}
     * @memberof RestActionParameters
     */
    'AwaitStatus'?: JobsTaskStatus;
    /**
     * 
     * @type {string}
     * @memberof RestActionParameters
     */
    'AwaitTimeout'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestActionParameters
     */
    'JsonParameters'?: string;
    /**
     * 
     * @type {Array<RestNodeLocator>}
     * @memberof RestActionParameters
     */
    'Nodes'?: Array<RestNodeLocator>;
    /**
     * 
     * @type {string}
     * @memberof RestActionParameters
     */
    'SelectionUuid'?: string;
    /**
     * 
     * @type {RestNodeLocator}
     * @memberof RestActionParameters
     */
    'TargetNode'?: RestNodeLocator;
}



