/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RestFilePreview
 */
export interface RestFilePreview {
    /**
     * 
     * @type {string}
     * @memberof RestFilePreview
     */
    'ContentType'?: string;
    /**
     * 
     * @type {number}
     * @memberof RestFilePreview
     */
    'Dimension'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RestFilePreview
     */
    'Processing'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RestFilePreview
     */
    'Url'?: string;
}

