/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MetaUpdateOp } from './meta-update-op';
// May contain unused imports in some cases
// @ts-ignore
import type { RestUserMeta } from './rest-user-meta';

/**
 * 
 * @export
 * @interface RestMetaUpdate
 */
export interface RestMetaUpdate {
    /**
     * 
     * @type {MetaUpdateOp}
     * @memberof RestMetaUpdate
     */
    'Operation': MetaUpdateOp;
    /**
     * 
     * @type {RestUserMeta}
     * @memberof RestMetaUpdate
     */
    'UserMeta': RestUserMeta;
}



