/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ServiceResourcePolicyAction } from './service-resource-policy-action';
// May contain unused imports in some cases
// @ts-ignore
import type { ServiceResourcePolicyPolicyEffect } from './service-resource-policy-policy-effect';

/**
 * 
 * @export
 * @interface ServiceResourcePolicy
 */
export interface ServiceResourcePolicy {
    /**
     * 
     * @type {ServiceResourcePolicyAction}
     * @memberof ServiceResourcePolicy
     */
    'Action'?: ServiceResourcePolicyAction;
    /**
     * 
     * @type {ServiceResourcePolicyPolicyEffect}
     * @memberof ServiceResourcePolicy
     */
    'Effect'?: ServiceResourcePolicyPolicyEffect;
    /**
     * 
     * @type {string}
     * @memberof ServiceResourcePolicy
     */
    'JsonConditions'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResourcePolicy
     */
    'Resource'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResourcePolicy
     */
    'Subject'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResourcePolicy
     */
    'id'?: string;
}



