/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TreeNode } from './tree-node';
// May contain unused imports in some cases
// @ts-ignore
import type { TreeNodeChangeEvent } from './tree-node-change-event';

/**
 * 
 * @export
 * @interface TreeChangeLog
 */
export interface TreeChangeLog {
    /**
     * 
     * @type {string}
     * @memberof TreeChangeLog
     */
    'Data'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeChangeLog
     */
    'Description'?: string;
    /**
     * 
     * @type {TreeNodeChangeEvent}
     * @memberof TreeChangeLog
     */
    'Event'?: TreeNodeChangeEvent;
    /**
     * 
     * @type {TreeNode}
     * @memberof TreeChangeLog
     */
    'Location'?: TreeNode;
    /**
     * 
     * @type {string}
     * @memberof TreeChangeLog
     */
    'MTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeChangeLog
     */
    'OwnerUuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeChangeLog
     */
    'Size'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeChangeLog
     */
    'Uuid'?: string;
}

