/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityOwnerType } from './ActivityOwnerType';
import {
    ActivityOwnerTypeFromJSON,
    ActivityOwnerTypeFromJSONTyped,
    ActivityOwnerTypeToJSON,
    ActivityOwnerTypeToJSONTyped,
} from './ActivityOwnerType';

/**
 * 
 * @export
 * @interface ActivitySubscription
 */
export interface ActivitySubscription {
    /**
     * 
     * @type {Array<string>}
     * @memberof ActivitySubscription
     */
    events?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ActivitySubscription
     */
    objectId?: string;
    /**
     * 
     * @type {ActivityOwnerType}
     * @memberof ActivitySubscription
     */
    objectType?: ActivityOwnerType;
    /**
     * 
     * @type {string}
     * @memberof ActivitySubscription
     */
    userId?: string;
}



/**
 * Check if a given object implements the ActivitySubscription interface.
 */
export function instanceOfActivitySubscription(value: object): value is ActivitySubscription {
    return true;
}

export function ActivitySubscriptionFromJSON(json: any): ActivitySubscription {
    return ActivitySubscriptionFromJSONTyped(json, false);
}

export function ActivitySubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivitySubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'events': json['Events'] == null ? undefined : json['Events'],
        'objectId': json['ObjectId'] == null ? undefined : json['ObjectId'],
        'objectType': json['ObjectType'] == null ? undefined : ActivityOwnerTypeFromJSON(json['ObjectType']),
        'userId': json['UserId'] == null ? undefined : json['UserId'],
    };
}

export function ActivitySubscriptionToJSON(json: any): ActivitySubscription {
    return ActivitySubscriptionToJSONTyped(json, false);
}

export function ActivitySubscriptionToJSONTyped(value?: ActivitySubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Events': value['events'],
        'ObjectId': value['objectId'],
        'ObjectType': ActivityOwnerTypeToJSON(value['objectType']),
        'UserId': value['userId'],
    };
}

