/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ActivityOwnerType = {
    Node: 'NODE',
    User: 'USER'
} as const;
export type ActivityOwnerType = typeof ActivityOwnerType[keyof typeof ActivityOwnerType];


export function instanceOfActivityOwnerType(value: any): boolean {
    for (const key in ActivityOwnerType) {
        if (Object.prototype.hasOwnProperty.call(ActivityOwnerType, key)) {
            if (ActivityOwnerType[key as keyof typeof ActivityOwnerType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ActivityOwnerTypeFromJSON(json: any): ActivityOwnerType {
    return ActivityOwnerTypeFromJSONTyped(json, false);
}

export function ActivityOwnerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityOwnerType {
    return json as ActivityOwnerType;
}

export function ActivityOwnerTypeToJSON(value?: ActivityOwnerType | null): any {
    return value as any;
}

export function ActivityOwnerTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ActivityOwnerType {
    return value as ActivityOwnerType;
}

