/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityObjectType } from './ActivityObjectType';
import {
    ActivityObjectTypeFromJSON,
    ActivityObjectTypeFromJSONTyped,
    ActivityObjectTypeToJSON,
    ActivityObjectTypeToJSONTyped,
} from './ActivityObjectType';

/**
 * 
 * @export
 * @interface ActivityObject
 */
export interface ActivityObject {
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    context?: string;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    accuracy?: number;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    actor?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    altitude?: number;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    anyOf?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    attachment?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    attributedTo?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    audience?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    bcc?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    bto?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    cc?: ActivityObject;
    /**
     * 
     * @type {Date}
     * @memberof ActivityObject
     */
    closed?: Date;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    content?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    context?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    current?: ActivityObject;
    /**
     * 
     * @type {Date}
     * @memberof ActivityObject
     */
    deleted?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ActivityObject
     */
    duration?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ActivityObject
     */
    endTime?: Date;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    first?: ActivityObject;
    /**
     * 
     * @type {ActivityObjectType}
     * @memberof ActivityObject
     */
    formerType?: ActivityObjectType;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    generator?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    href?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    hreflang?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    icon?: ActivityObject;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    id?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    image?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    inReplyTo?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    instrument?: ActivityObject;
    /**
     * 
     * @type {Array<ActivityObject>}
     * @memberof ActivityObject
     */
    items?: Array<ActivityObject>;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    last?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    latitude?: number;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    location?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    longitude?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    markdown?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    mediaType?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    name?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    next?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    object?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    oneOf?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    origin?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    partOf?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    prev?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    preview?: ActivityObject;
    /**
     * 
     * @type {Date}
     * @memberof ActivityObject
     */
    published?: Date;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    radius?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    rel?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    relationship?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    replies?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    result?: ActivityObject;
    /**
     * 
     * @type {Date}
     * @memberof ActivityObject
     */
    startTime?: Date;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    subject?: ActivityObject;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    summary?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    tag?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    target?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    to?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    totalItems?: number;
    /**
     * 
     * @type {ActivityObjectType}
     * @memberof ActivityObject
     */
    type?: ActivityObjectType;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    units?: string;
    /**
     * 
     * @type {Date}
     * @memberof ActivityObject
     */
    updated?: Date;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    url?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    width?: number;
}



/**
 * Check if a given object implements the ActivityObject interface.
 */
export function instanceOfActivityObject(value: object): value is ActivityObject {
    return true;
}

export function ActivityObjectFromJSON(json: any): ActivityObject {
    return ActivityObjectFromJSONTyped(json, false);
}

export function ActivityObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityObject {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['@context'] == null ? undefined : json['@context'],
        'accuracy': json['accuracy'] == null ? undefined : json['accuracy'],
        'actor': json['actor'] == null ? undefined : ActivityObjectFromJSON(json['actor']),
        'altitude': json['altitude'] == null ? undefined : json['altitude'],
        'anyOf': json['anyOf'] == null ? undefined : ActivityObjectFromJSON(json['anyOf']),
        'attachment': json['attachment'] == null ? undefined : ActivityObjectFromJSON(json['attachment']),
        'attributedTo': json['attributedTo'] == null ? undefined : ActivityObjectFromJSON(json['attributedTo']),
        'audience': json['audience'] == null ? undefined : ActivityObjectFromJSON(json['audience']),
        'bcc': json['bcc'] == null ? undefined : ActivityObjectFromJSON(json['bcc']),
        'bto': json['bto'] == null ? undefined : ActivityObjectFromJSON(json['bto']),
        'cc': json['cc'] == null ? undefined : ActivityObjectFromJSON(json['cc']),
        'closed': json['closed'] == null ? undefined : (new Date(json['closed'])),
        'content': json['content'] == null ? undefined : ActivityObjectFromJSON(json['content']),
        'context': json['context'] == null ? undefined : ActivityObjectFromJSON(json['context']),
        'current': json['current'] == null ? undefined : ActivityObjectFromJSON(json['current']),
        'deleted': json['deleted'] == null ? undefined : (new Date(json['deleted'])),
        'duration': json['duration'] == null ? undefined : (new Date(json['duration'])),
        'endTime': json['endTime'] == null ? undefined : (new Date(json['endTime'])),
        'first': json['first'] == null ? undefined : ActivityObjectFromJSON(json['first']),
        'formerType': json['formerType'] == null ? undefined : ActivityObjectTypeFromJSON(json['formerType']),
        'generator': json['generator'] == null ? undefined : ActivityObjectFromJSON(json['generator']),
        'height': json['height'] == null ? undefined : json['height'],
        'href': json['href'] == null ? undefined : json['href'],
        'hreflang': json['hreflang'] == null ? undefined : json['hreflang'],
        'icon': json['icon'] == null ? undefined : ActivityObjectFromJSON(json['icon']),
        'id': json['id'] == null ? undefined : json['id'],
        'image': json['image'] == null ? undefined : ActivityObjectFromJSON(json['image']),
        'inReplyTo': json['inReplyTo'] == null ? undefined : ActivityObjectFromJSON(json['inReplyTo']),
        'instrument': json['instrument'] == null ? undefined : ActivityObjectFromJSON(json['instrument']),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ActivityObjectFromJSON)),
        'last': json['last'] == null ? undefined : ActivityObjectFromJSON(json['last']),
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'location': json['location'] == null ? undefined : ActivityObjectFromJSON(json['location']),
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'markdown': json['markdown'] == null ? undefined : json['markdown'],
        'mediaType': json['mediaType'] == null ? undefined : json['mediaType'],
        'name': json['name'] == null ? undefined : json['name'],
        'next': json['next'] == null ? undefined : ActivityObjectFromJSON(json['next']),
        'object': json['object'] == null ? undefined : ActivityObjectFromJSON(json['object']),
        'oneOf': json['oneOf'] == null ? undefined : ActivityObjectFromJSON(json['oneOf']),
        'origin': json['origin'] == null ? undefined : ActivityObjectFromJSON(json['origin']),
        'partOf': json['partOf'] == null ? undefined : ActivityObjectFromJSON(json['partOf']),
        'prev': json['prev'] == null ? undefined : ActivityObjectFromJSON(json['prev']),
        'preview': json['preview'] == null ? undefined : ActivityObjectFromJSON(json['preview']),
        'published': json['published'] == null ? undefined : (new Date(json['published'])),
        'radius': json['radius'] == null ? undefined : json['radius'],
        'rel': json['rel'] == null ? undefined : json['rel'],
        'relationship': json['relationship'] == null ? undefined : ActivityObjectFromJSON(json['relationship']),
        'replies': json['replies'] == null ? undefined : ActivityObjectFromJSON(json['replies']),
        'result': json['result'] == null ? undefined : ActivityObjectFromJSON(json['result']),
        'startTime': json['startTime'] == null ? undefined : (new Date(json['startTime'])),
        'subject': json['subject'] == null ? undefined : ActivityObjectFromJSON(json['subject']),
        'summary': json['summary'] == null ? undefined : json['summary'],
        'tag': json['tag'] == null ? undefined : ActivityObjectFromJSON(json['tag']),
        'target': json['target'] == null ? undefined : ActivityObjectFromJSON(json['target']),
        'to': json['to'] == null ? undefined : ActivityObjectFromJSON(json['to']),
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'type': json['type'] == null ? undefined : ActivityObjectTypeFromJSON(json['type']),
        'units': json['units'] == null ? undefined : json['units'],
        'updated': json['updated'] == null ? undefined : (new Date(json['updated'])),
        'url': json['url'] == null ? undefined : ActivityObjectFromJSON(json['url']),
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function ActivityObjectToJSON(json: any): ActivityObject {
    return ActivityObjectToJSONTyped(json, false);
}

export function ActivityObjectToJSONTyped(value?: ActivityObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@context': value['context'],
        'accuracy': value['accuracy'],
        'actor': ActivityObjectToJSON(value['actor']),
        'altitude': value['altitude'],
        'anyOf': ActivityObjectToJSON(value['anyOf']),
        'attachment': ActivityObjectToJSON(value['attachment']),
        'attributedTo': ActivityObjectToJSON(value['attributedTo']),
        'audience': ActivityObjectToJSON(value['audience']),
        'bcc': ActivityObjectToJSON(value['bcc']),
        'bto': ActivityObjectToJSON(value['bto']),
        'cc': ActivityObjectToJSON(value['cc']),
        'closed': value['closed'] == null ? undefined : ((value['closed']).toISOString()),
        'content': ActivityObjectToJSON(value['content']),
        'context': ActivityObjectToJSON(value['context']),
        'current': ActivityObjectToJSON(value['current']),
        'deleted': value['deleted'] == null ? undefined : ((value['deleted']).toISOString()),
        'duration': value['duration'] == null ? undefined : ((value['duration']).toISOString()),
        'endTime': value['endTime'] == null ? undefined : ((value['endTime']).toISOString()),
        'first': ActivityObjectToJSON(value['first']),
        'formerType': ActivityObjectTypeToJSON(value['formerType']),
        'generator': ActivityObjectToJSON(value['generator']),
        'height': value['height'],
        'href': value['href'],
        'hreflang': value['hreflang'],
        'icon': ActivityObjectToJSON(value['icon']),
        'id': value['id'],
        'image': ActivityObjectToJSON(value['image']),
        'inReplyTo': ActivityObjectToJSON(value['inReplyTo']),
        'instrument': ActivityObjectToJSON(value['instrument']),
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ActivityObjectToJSON)),
        'last': ActivityObjectToJSON(value['last']),
        'latitude': value['latitude'],
        'location': ActivityObjectToJSON(value['location']),
        'longitude': value['longitude'],
        'markdown': value['markdown'],
        'mediaType': value['mediaType'],
        'name': value['name'],
        'next': ActivityObjectToJSON(value['next']),
        'object': ActivityObjectToJSON(value['object']),
        'oneOf': ActivityObjectToJSON(value['oneOf']),
        'origin': ActivityObjectToJSON(value['origin']),
        'partOf': ActivityObjectToJSON(value['partOf']),
        'prev': ActivityObjectToJSON(value['prev']),
        'preview': ActivityObjectToJSON(value['preview']),
        'published': value['published'] == null ? undefined : ((value['published']).toISOString()),
        'radius': value['radius'],
        'rel': value['rel'],
        'relationship': ActivityObjectToJSON(value['relationship']),
        'replies': ActivityObjectToJSON(value['replies']),
        'result': ActivityObjectToJSON(value['result']),
        'startTime': value['startTime'] == null ? undefined : ((value['startTime']).toISOString()),
        'subject': ActivityObjectToJSON(value['subject']),
        'summary': value['summary'],
        'tag': ActivityObjectToJSON(value['tag']),
        'target': ActivityObjectToJSON(value['target']),
        'to': ActivityObjectToJSON(value['to']),
        'totalItems': value['totalItems'],
        'type': ActivityObjectTypeToJSON(value['type']),
        'units': value['units'],
        'updated': value['updated'] == null ? undefined : ((value['updated']).toISOString()),
        'url': ActivityObjectToJSON(value['url']),
        'width': value['width'],
    };
}

