/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceQuery } from './ServiceQuery';
import {
    ServiceQueryFromJSON,
    ServiceQueryFromJSONTyped,
    ServiceQueryToJSON,
    ServiceQueryToJSONTyped,
} from './ServiceQuery';

/**
 * 
 * @export
 * @interface JobsDataSelector
 */
export interface JobsDataSelector {
    /**
     * 
     * @type {boolean}
     * @memberof JobsDataSelector
     */
    clearInput?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JobsDataSelector
     */
    collect?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobsDataSelector
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof JobsDataSelector
     */
    fanOutInput?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobsDataSelector
     */
    label?: string;
    /**
     * 
     * @type {ServiceQuery}
     * @memberof JobsDataSelector
     */
    query?: ServiceQuery;
    /**
     * 
     * @type {string}
     * @memberof JobsDataSelector
     */
    timeout?: string;
}

/**
 * Check if a given object implements the JobsDataSelector interface.
 */
export function instanceOfJobsDataSelector(value: object): value is JobsDataSelector {
    return true;
}

export function JobsDataSelectorFromJSON(json: any): JobsDataSelector {
    return JobsDataSelectorFromJSONTyped(json, false);
}

export function JobsDataSelectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsDataSelector {
    if (json == null) {
        return json;
    }
    return {
        
        'clearInput': json['ClearInput'] == null ? undefined : json['ClearInput'],
        'collect': json['Collect'] == null ? undefined : json['Collect'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'fanOutInput': json['FanOutInput'] == null ? undefined : json['FanOutInput'],
        'label': json['Label'] == null ? undefined : json['Label'],
        'query': json['Query'] == null ? undefined : ServiceQueryFromJSON(json['Query']),
        'timeout': json['Timeout'] == null ? undefined : json['Timeout'],
    };
}

export function JobsDataSelectorToJSON(json: any): JobsDataSelector {
    return JobsDataSelectorToJSONTyped(json, false);
}

export function JobsDataSelectorToJSONTyped(value?: JobsDataSelector | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ClearInput': value['clearInput'],
        'Collect': value['collect'],
        'Description': value['description'],
        'FanOutInput': value['fanOutInput'],
        'Label': value['label'],
        'Query': ServiceQueryToJSON(value['query']),
        'Timeout': value['timeout'],
    };
}

