/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobsCommand } from './JobsCommand';
import {
    JobsCommandFromJSON,
    JobsCommandFromJSONTyped,
    JobsCommandToJSON,
    JobsCommandToJSONTyped,
} from './JobsCommand';

/**
 * 
 * @export
 * @interface JobsCtrlCommand
 */
export interface JobsCtrlCommand {
    /**
     * 
     * @type {JobsCommand}
     * @memberof JobsCtrlCommand
     */
    cmd?: JobsCommand;
    /**
     * 
     * @type {string}
     * @memberof JobsCtrlCommand
     */
    jobId?: string;
    /**
     * 
     * @type {string}
     * @memberof JobsCtrlCommand
     */
    ownerId?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof JobsCtrlCommand
     */
    runParameters?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof JobsCtrlCommand
     */
    taskId?: string;
}



/**
 * Check if a given object implements the JobsCtrlCommand interface.
 */
export function instanceOfJobsCtrlCommand(value: object): value is JobsCtrlCommand {
    return true;
}

export function JobsCtrlCommandFromJSON(json: any): JobsCtrlCommand {
    return JobsCtrlCommandFromJSONTyped(json, false);
}

export function JobsCtrlCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsCtrlCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'cmd': json['Cmd'] == null ? undefined : JobsCommandFromJSON(json['Cmd']),
        'jobId': json['JobId'] == null ? undefined : json['JobId'],
        'ownerId': json['OwnerId'] == null ? undefined : json['OwnerId'],
        'runParameters': json['RunParameters'] == null ? undefined : json['RunParameters'],
        'taskId': json['TaskId'] == null ? undefined : json['TaskId'],
    };
}

export function JobsCtrlCommandToJSON(json: any): JobsCtrlCommand {
    return JobsCtrlCommandToJSONTyped(json, false);
}

export function JobsCtrlCommandToJSONTyped(value?: JobsCtrlCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Cmd': JobsCommandToJSON(value['cmd']),
        'JobId': value['jobId'],
        'OwnerId': value['ownerId'],
        'RunParameters': value['runParameters'],
        'TaskId': value['taskId'],
    };
}

