/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobsAction } from './JobsAction';
import {
    JobsActionFromJSON,
    JobsActionFromJSONTyped,
    JobsActionToJSON,
    JobsActionToJSONTyped,
} from './JobsAction';
import type { JobsActionMessage } from './JobsActionMessage';
import {
    JobsActionMessageFromJSON,
    JobsActionMessageFromJSONTyped,
    JobsActionMessageToJSON,
    JobsActionMessageToJSONTyped,
} from './JobsActionMessage';

/**
 * 
 * @export
 * @interface JobsActionLog
 */
export interface JobsActionLog {
    /**
     * 
     * @type {JobsAction}
     * @memberof JobsActionLog
     */
    action?: JobsAction;
    /**
     * 
     * @type {JobsActionMessage}
     * @memberof JobsActionLog
     */
    inputMessage?: JobsActionMessage;
    /**
     * 
     * @type {JobsActionMessage}
     * @memberof JobsActionLog
     */
    outputMessage?: JobsActionMessage;
}

/**
 * Check if a given object implements the JobsActionLog interface.
 */
export function instanceOfJobsActionLog(value: object): value is JobsActionLog {
    return true;
}

export function JobsActionLogFromJSON(json: any): JobsActionLog {
    return JobsActionLogFromJSONTyped(json, false);
}

export function JobsActionLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsActionLog {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['Action'] == null ? undefined : JobsActionFromJSON(json['Action']),
        'inputMessage': json['InputMessage'] == null ? undefined : JobsActionMessageFromJSON(json['InputMessage']),
        'outputMessage': json['OutputMessage'] == null ? undefined : JobsActionMessageFromJSON(json['OutputMessage']),
    };
}

export function JobsActionLogToJSON(json: any): JobsActionLog {
    return JobsActionLogToJSONTyped(json, false);
}

export function JobsActionLogToJSONTyped(value?: JobsActionLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Action': JobsActionToJSON(value['action']),
        'InputMessage': JobsActionMessageToJSON(value['inputMessage']),
        'OutputMessage': JobsActionMessageToJSON(value['outputMessage']),
    };
}

