/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobsCommand = {
    None: 'None',
    Pause: 'Pause',
    Resume: 'Resume',
    Stop: 'Stop',
    Delete: 'Delete',
    RunOnce: 'RunOnce',
    Inactive: 'Inactive',
    Active: 'Active'
} as const;
export type JobsCommand = typeof JobsCommand[keyof typeof JobsCommand];


export function instanceOfJobsCommand(value: any): boolean {
    for (const key in JobsCommand) {
        if (Object.prototype.hasOwnProperty.call(JobsCommand, key)) {
            if (JobsCommand[key as keyof typeof JobsCommand] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobsCommandFromJSON(json: any): JobsCommand {
    return JobsCommandFromJSONTyped(json, false);
}

export function JobsCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsCommand {
    return json as JobsCommand;
}

export function JobsCommandToJSON(value?: JobsCommand | null): any {
    return value as any;
}

export function JobsCommandToJSONTyped(value: any, ignoreDiscriminator: boolean): JobsCommand {
    return value as JobsCommand;
}

