/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ObjectEncryptionMode = {
    Clear: 'CLEAR',
    Master: 'MASTER',
    User: 'USER',
    UserPwd: 'USER_PWD'
} as const;
export type ObjectEncryptionMode = typeof ObjectEncryptionMode[keyof typeof ObjectEncryptionMode];


export function instanceOfObjectEncryptionMode(value: any): boolean {
    for (const key in ObjectEncryptionMode) {
        if (Object.prototype.hasOwnProperty.call(ObjectEncryptionMode, key)) {
            if (ObjectEncryptionMode[key as keyof typeof ObjectEncryptionMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ObjectEncryptionModeFromJSON(json: any): ObjectEncryptionMode {
    return ObjectEncryptionModeFromJSONTyped(json, false);
}

export function ObjectEncryptionModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectEncryptionMode {
    return json as ObjectEncryptionMode;
}

export function ObjectEncryptionModeToJSON(value?: ObjectEncryptionMode | null): any {
    return value as any;
}

export function ObjectEncryptionModeToJSONTyped(value: any, ignoreDiscriminator: boolean): ObjectEncryptionMode {
    return value as ObjectEncryptionMode;
}

