/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ObjectStorageType = {
    Local: 'LOCAL',
    S3: 'S3',
    Smb: 'SMB',
    Cells: 'CELLS',
    Azure: 'AZURE',
    Gcs: 'GCS',
    B2: 'B2',
    Manta: 'MANTA',
    Sia: 'SIA'
} as const;
export type ObjectStorageType = typeof ObjectStorageType[keyof typeof ObjectStorageType];


export function instanceOfObjectStorageType(value: any): boolean {
    for (const key in ObjectStorageType) {
        if (Object.prototype.hasOwnProperty.call(ObjectStorageType, key)) {
            if (ObjectStorageType[key as keyof typeof ObjectStorageType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ObjectStorageTypeFromJSON(json: any): ObjectStorageType {
    return ObjectStorageTypeFromJSONTyped(json, false);
}

export function ObjectStorageTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectStorageType {
    return json as ObjectStorageType;
}

export function ObjectStorageTypeToJSON(value?: ObjectStorageType | null): any {
    return value as any;
}

export function ObjectStorageTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ObjectStorageType {
    return value as ObjectStorageType;
}

