/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TreeNode } from './TreeNode';
import {
    TreeNodeFromJSON,
    TreeNodeFromJSONTyped,
    TreeNodeToJSON,
    TreeNodeToJSONTyped,
} from './TreeNode';

/**
 * 
 * @export
 * @interface RestNodesCollection
 */
export interface RestNodesCollection {
    /**
     * 
     * @type {Array<TreeNode>}
     * @memberof RestNodesCollection
     */
    children?: Array<TreeNode>;
    /**
     * 
     * @type {TreeNode}
     * @memberof RestNodesCollection
     */
    parent?: TreeNode;
}

/**
 * Check if a given object implements the RestNodesCollection interface.
 */
export function instanceOfRestNodesCollection(value: object): value is RestNodesCollection {
    return true;
}

export function RestNodesCollectionFromJSON(json: any): RestNodesCollection {
    return RestNodesCollectionFromJSONTyped(json, false);
}

export function RestNodesCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestNodesCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'children': json['Children'] == null ? undefined : ((json['Children'] as Array<any>).map(TreeNodeFromJSON)),
        'parent': json['Parent'] == null ? undefined : TreeNodeFromJSON(json['Parent']),
    };
}

export function RestNodesCollectionToJSON(json: any): RestNodesCollection {
    return RestNodesCollectionToJSONTyped(json, false);
}

export function RestNodesCollectionToJSONTyped(value?: RestNodesCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(TreeNodeToJSON)),
        'Parent': TreeNodeToJSON(value['parent']),
    };
}

