/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestCountMeta
 */
export interface RestCountMeta {
    /**
     * 
     * @type {string}
     * @memberof RestCountMeta
     */
    namespace: string;
    /**
     * 
     * @type {number}
     * @memberof RestCountMeta
     */
    value: number;
}

/**
 * Check if a given object implements the RestCountMeta interface.
 */
export function instanceOfRestCountMeta(value: object): value is RestCountMeta {
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function RestCountMetaFromJSON(json: any): RestCountMeta {
    return RestCountMetaFromJSONTyped(json, false);
}

export function RestCountMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestCountMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'namespace': json['Namespace'],
        'value': json['Value'],
    };
}

export function RestCountMetaToJSON(json: any): RestCountMeta {
    return RestCountMetaToJSONTyped(json, false);
}

export function RestCountMetaToJSONTyped(value?: RestCountMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Namespace': value['namespace'],
        'Value': value['value'],
    };
}

