/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RestActionStatus = {
    Performed: 'Performed',
    Background: 'Background'
} as const;
export type RestActionStatus = typeof RestActionStatus[keyof typeof RestActionStatus];


export function instanceOfRestActionStatus(value: any): boolean {
    for (const key in RestActionStatus) {
        if (Object.prototype.hasOwnProperty.call(RestActionStatus, key)) {
            if (RestActionStatus[key as keyof typeof RestActionStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RestActionStatusFromJSON(json: any): RestActionStatus {
    return RestActionStatusFromJSONTyped(json, false);
}

export function RestActionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestActionStatus {
    return json as RestActionStatus;
}

export function RestActionStatusToJSON(value?: RestActionStatus | null): any {
    return value as any;
}

export function RestActionStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RestActionStatus {
    return value as RestActionStatus;
}

