/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestCheckResult } from './RestCheckResult';
import {
    RestCheckResultFromJSON,
    RestCheckResultFromJSONTyped,
    RestCheckResultToJSON,
    RestCheckResultToJSONTyped,
} from './RestCheckResult';

/**
 * 
 * @export
 * @interface RestCreateCheckResponse
 */
export interface RestCreateCheckResponse {
    /**
     * 
     * @type {Array<RestCheckResult>}
     * @memberof RestCreateCheckResponse
     */
    results: Array<RestCheckResult>;
}

/**
 * Check if a given object implements the RestCreateCheckResponse interface.
 */
export function instanceOfRestCreateCheckResponse(value: object): value is RestCreateCheckResponse {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function RestCreateCheckResponseFromJSON(json: any): RestCreateCheckResponse {
    return RestCreateCheckResponseFromJSONTyped(json, false);
}

export function RestCreateCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestCreateCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['Results'] as Array<any>).map(RestCheckResultFromJSON)),
    };
}

export function RestCreateCheckResponseToJSON(json: any): RestCreateCheckResponse {
    return RestCreateCheckResponseToJSONTyped(json, false);
}

export function RestCreateCheckResponseToJSONTyped(value?: RestCreateCheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Results': ((value['results'] as Array<any>).map(RestCheckResultToJSON)),
    };
}

