/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobsTaskStatus } from './JobsTaskStatus';
import {
    JobsTaskStatusFromJSON,
    JobsTaskStatusFromJSONTyped,
    JobsTaskStatusToJSON,
    JobsTaskStatusToJSONTyped,
} from './JobsTaskStatus';

/**
 * 
 * @export
 * @interface RestBackgroundAction
 */
export interface RestBackgroundAction {
    /**
     * 
     * @type {boolean}
     * @memberof RestBackgroundAction
     */
    canPause?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RestBackgroundAction
     */
    canStop?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RestBackgroundAction
     */
    endTime?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RestBackgroundAction
     */
    hasProgress?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RestBackgroundAction
     */
    jobUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof RestBackgroundAction
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof RestBackgroundAction
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof RestBackgroundAction
     */
    progress?: number;
    /**
     * 
     * @type {number}
     * @memberof RestBackgroundAction
     */
    startTime?: number;
    /**
     * 
     * @type {JobsTaskStatus}
     * @memberof RestBackgroundAction
     */
    status?: JobsTaskStatus;
    /**
     * 
     * @type {string}
     * @memberof RestBackgroundAction
     */
    statusMessage?: string;
}



/**
 * Check if a given object implements the RestBackgroundAction interface.
 */
export function instanceOfRestBackgroundAction(value: object): value is RestBackgroundAction {
    return true;
}

export function RestBackgroundActionFromJSON(json: any): RestBackgroundAction {
    return RestBackgroundActionFromJSONTyped(json, false);
}

export function RestBackgroundActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestBackgroundAction {
    if (json == null) {
        return json;
    }
    return {
        
        'canPause': json['CanPause'] == null ? undefined : json['CanPause'],
        'canStop': json['CanStop'] == null ? undefined : json['CanStop'],
        'endTime': json['EndTime'] == null ? undefined : json['EndTime'],
        'hasProgress': json['HasProgress'] == null ? undefined : json['HasProgress'],
        'jobUuid': json['JobUuid'] == null ? undefined : json['JobUuid'],
        'label': json['Label'] == null ? undefined : json['Label'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'progress': json['Progress'] == null ? undefined : json['Progress'],
        'startTime': json['StartTime'] == null ? undefined : json['StartTime'],
        'status': json['Status'] == null ? undefined : JobsTaskStatusFromJSON(json['Status']),
        'statusMessage': json['StatusMessage'] == null ? undefined : json['StatusMessage'],
    };
}

export function RestBackgroundActionToJSON(json: any): RestBackgroundAction {
    return RestBackgroundActionToJSONTyped(json, false);
}

export function RestBackgroundActionToJSONTyped(value?: RestBackgroundAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'CanPause': value['canPause'],
        'CanStop': value['canStop'],
        'EndTime': value['endTime'],
        'HasProgress': value['hasProgress'],
        'JobUuid': value['jobUuid'],
        'Label': value['label'],
        'Name': value['name'],
        'Progress': value['progress'],
        'StartTime': value['startTime'],
        'Status': JobsTaskStatusToJSON(value['status']),
        'StatusMessage': value['statusMessage'],
    };
}

