/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestMetaToggle
 */
export interface RestMetaToggle {
    /**
     * 
     * @type {boolean}
     * @memberof RestMetaToggle
     */
    value: boolean;
}

/**
 * Check if a given object implements the RestMetaToggle interface.
 */
export function instanceOfRestMetaToggle(value: object): value is RestMetaToggle {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function RestMetaToggleFromJSON(json: any): RestMetaToggle {
    return RestMetaToggleFromJSONTyped(json, false);
}

export function RestMetaToggleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestMetaToggle {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['Value'],
    };
}

export function RestMetaToggleToJSON(json: any): RestMetaToggle {
    return RestMetaToggleToJSONTyped(json, false);
}

export function RestMetaToggleToJSONTyped(value?: RestMetaToggle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Value': value['value'],
    };
}

