/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestNodeLocator
 */
export interface RestNodeLocator {
    /**
     * 
     * @type {string}
     * @memberof RestNodeLocator
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof RestNodeLocator
     */
    uuid?: string;
}

/**
 * Check if a given object implements the RestNodeLocator interface.
 */
export function instanceOfRestNodeLocator(value: object): value is RestNodeLocator {
    return true;
}

export function RestNodeLocatorFromJSON(json: any): RestNodeLocator {
    return RestNodeLocatorFromJSONTyped(json, false);
}

export function RestNodeLocatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestNodeLocator {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['Path'] == null ? undefined : json['Path'],
        'uuid': json['Uuid'] == null ? undefined : json['Uuid'],
    };
}

export function RestNodeLocatorToJSON(json: any): RestNodeLocator {
    return RestNodeLocatorToJSONTyped(json, false);
}

export function RestNodeLocatorToJSONTyped(value?: RestNodeLocator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Path': value['path'],
        'Uuid': value['uuid'],
    };
}

