/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestUserMeta
 */
export interface RestUserMeta {
    /**
     * 
     * @type {boolean}
     * @memberof RestUserMeta
     */
    editable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RestUserMeta
     */
    jsonValue?: string;
    /**
     * 
     * @type {string}
     * @memberof RestUserMeta
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof RestUserMeta
     */
    nodeUuid?: string;
}

/**
 * Check if a given object implements the RestUserMeta interface.
 */
export function instanceOfRestUserMeta(value: object): value is RestUserMeta {
    return true;
}

export function RestUserMetaFromJSON(json: any): RestUserMeta {
    return RestUserMetaFromJSONTyped(json, false);
}

export function RestUserMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestUserMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'editable': json['Editable'] == null ? undefined : json['Editable'],
        'jsonValue': json['JsonValue'] == null ? undefined : json['JsonValue'],
        'namespace': json['Namespace'] == null ? undefined : json['Namespace'],
        'nodeUuid': json['NodeUuid'] == null ? undefined : json['NodeUuid'],
    };
}

export function RestUserMetaToJSON(json: any): RestUserMeta {
    return RestUserMetaToJSONTyped(json, false);
}

export function RestUserMetaToJSONTyped(value?: RestUserMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Editable': value['editable'],
        'JsonValue': value['jsonValue'],
        'Namespace': value['namespace'],
        'NodeUuid': value['nodeUuid'],
    };
}

