/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RestMode = {
    Default: 'Default',
    NodeReadOnly: 'NodeReadOnly',
    NodeWriteOnly: 'NodeWriteOnly',
    LevelReadOnly: 'LevelReadOnly'
} as const;
export type RestMode = typeof RestMode[keyof typeof RestMode];


export function instanceOfRestMode(value: any): boolean {
    for (const key in RestMode) {
        if (Object.prototype.hasOwnProperty.call(RestMode, key)) {
            if (RestMode[key as keyof typeof RestMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RestModeFromJSON(json: any): RestMode {
    return RestModeFromJSONTyped(json, false);
}

export function RestModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestMode {
    return json as RestMode;
}

export function RestModeToJSON(value?: RestMode | null): any {
    return value as any;
}

export function RestModeToJSONTyped(value: any, ignoreDiscriminator: boolean): RestMode {
    return value as RestMode;
}

