/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestNode } from './RestNode';
import {
    RestNodeFromJSON,
    RestNodeFromJSONTyped,
    RestNodeToJSON,
    RestNodeToJSONTyped,
} from './RestNode';

/**
 * Request to create a selection from a list of nodes.
 * @export
 * @interface RestSelection
 */
export interface RestSelection {
    /**
     * 
     * @type {Array<RestNode>}
     * @memberof RestSelection
     */
    nodes: Array<RestNode>;
    /**
     * 
     * @type {string}
     * @memberof RestSelection
     */
    readonly uuid?: string;
}

/**
 * Check if a given object implements the RestSelection interface.
 */
export function instanceOfRestSelection(value: object): value is RestSelection {
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    return true;
}

export function RestSelectionFromJSON(json: any): RestSelection {
    return RestSelectionFromJSONTyped(json, false);
}

export function RestSelectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestSelection {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': ((json['Nodes'] as Array<any>).map(RestNodeFromJSON)),
        'uuid': json['Uuid'] == null ? undefined : json['Uuid'],
    };
}

export function RestSelectionToJSON(json: any): RestSelection {
    return RestSelectionToJSONTyped(json, false);
}

export function RestSelectionToJSONTyped(value?: Omit<RestSelection, 'Uuid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Nodes': ((value['nodes'] as Array<any>).map(RestNodeToJSON)),
    };
}

