/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestNodeLocator } from './RestNodeLocator';
import {
    RestNodeLocatorFromJSON,
    RestNodeLocatorFromJSONTyped,
    RestNodeLocatorToJSON,
    RestNodeLocatorToJSONTyped,
} from './RestNodeLocator';

/**
 * 
 * @export
 * @interface RestNodeLocators
 */
export interface RestNodeLocators {
    /**
     * 
     * @type {Array<RestNodeLocator>}
     * @memberof RestNodeLocators
     */
    many?: Array<RestNodeLocator>;
}

/**
 * Check if a given object implements the RestNodeLocators interface.
 */
export function instanceOfRestNodeLocators(value: object): value is RestNodeLocators {
    return true;
}

export function RestNodeLocatorsFromJSON(json: any): RestNodeLocators {
    return RestNodeLocatorsFromJSONTyped(json, false);
}

export function RestNodeLocatorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestNodeLocators {
    if (json == null) {
        return json;
    }
    return {
        
        'many': json['Many'] == null ? undefined : ((json['Many'] as Array<any>).map(RestNodeLocatorFromJSON)),
    };
}

export function RestNodeLocatorsToJSON(json: any): RestNodeLocators {
    return RestNodeLocatorsToJSONTyped(json, false);
}

export function RestNodeLocatorsToJSONTyped(value?: RestNodeLocators | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Many': value['many'] == null ? undefined : ((value['many'] as Array<any>).map(RestNodeLocatorToJSON)),
    };
}

