/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestBackgroundAction } from './RestBackgroundAction';
import {
    RestBackgroundActionFromJSON,
    RestBackgroundActionFromJSONTyped,
    RestBackgroundActionToJSON,
    RestBackgroundActionToJSONTyped,
} from './RestBackgroundAction';
import type { RestNode } from './RestNode';
import {
    RestNodeFromJSON,
    RestNodeFromJSONTyped,
    RestNodeToJSON,
    RestNodeToJSONTyped,
} from './RestNode';
import type { RestActionStatus } from './RestActionStatus';
import {
    RestActionStatusFromJSON,
    RestActionStatusFromJSONTyped,
    RestActionStatusToJSON,
    RestActionStatusToJSONTyped,
} from './RestActionStatus';

/**
 * 
 * @export
 * @interface RestPerformActionResponse
 */
export interface RestPerformActionResponse {
    /**
     * 
     * @type {Array<RestNode>}
     * @memberof RestPerformActionResponse
     */
    affectedNodes?: Array<RestNode>;
    /**
     * 
     * @type {RestActionStatus}
     * @memberof RestPerformActionResponse
     */
    status?: RestActionStatus;
    /**
     * 
     * @type {Array<RestBackgroundAction>}
     * @memberof RestPerformActionResponse
     */
    tasks?: Array<RestBackgroundAction>;
}



/**
 * Check if a given object implements the RestPerformActionResponse interface.
 */
export function instanceOfRestPerformActionResponse(value: object): value is RestPerformActionResponse {
    return true;
}

export function RestPerformActionResponseFromJSON(json: any): RestPerformActionResponse {
    return RestPerformActionResponseFromJSONTyped(json, false);
}

export function RestPerformActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestPerformActionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'affectedNodes': json['AffectedNodes'] == null ? undefined : ((json['AffectedNodes'] as Array<any>).map(RestNodeFromJSON)),
        'status': json['Status'] == null ? undefined : RestActionStatusFromJSON(json['Status']),
        'tasks': json['Tasks'] == null ? undefined : ((json['Tasks'] as Array<any>).map(RestBackgroundActionFromJSON)),
    };
}

export function RestPerformActionResponseToJSON(json: any): RestPerformActionResponse {
    return RestPerformActionResponseToJSONTyped(json, false);
}

export function RestPerformActionResponseToJSONTyped(value?: RestPerformActionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AffectedNodes': value['affectedNodes'] == null ? undefined : ((value['affectedNodes'] as Array<any>).map(RestNodeToJSON)),
        'Status': RestActionStatusToJSON(value['status']),
        'Tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(RestBackgroundActionToJSON)),
    };
}

