/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RestUserActionType = {
    Delete: 'delete',
    Restore: 'restore',
    Copy: 'copy',
    Move: 'move',
    Extract: 'extract',
    Compress: 'compress'
} as const;
export type RestUserActionType = typeof RestUserActionType[keyof typeof RestUserActionType];


export function instanceOfRestUserActionType(value: any): boolean {
    for (const key in RestUserActionType) {
        if (Object.prototype.hasOwnProperty.call(RestUserActionType, key)) {
            if (RestUserActionType[key as keyof typeof RestUserActionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RestUserActionTypeFromJSON(json: any): RestUserActionType {
    return RestUserActionTypeFromJSONTyped(json, false);
}

export function RestUserActionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestUserActionType {
    return json as RestUserActionType;
}

export function RestUserActionTypeToJSON(value?: RestUserActionType | null): any {
    return value as any;
}

export function RestUserActionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): RestUserActionType {
    return value as RestUserActionType;
}

