/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestMetaUpdate } from './RestMetaUpdate';
import {
    RestMetaUpdateFromJSON,
    RestMetaUpdateFromJSONTyped,
    RestMetaUpdateToJSON,
    RestMetaUpdateToJSONTyped,
} from './RestMetaUpdate';

/**
 * 
 * @export
 * @interface RestBatchUpdateMetaList
 */
export interface RestBatchUpdateMetaList {
    /**
     * 
     * @type {Array<RestMetaUpdate>}
     * @memberof RestBatchUpdateMetaList
     */
    updates: Array<RestMetaUpdate>;
}

/**
 * Check if a given object implements the RestBatchUpdateMetaList interface.
 */
export function instanceOfRestBatchUpdateMetaList(value: object): value is RestBatchUpdateMetaList {
    if (!('updates' in value) || value['updates'] === undefined) return false;
    return true;
}

export function RestBatchUpdateMetaListFromJSON(json: any): RestBatchUpdateMetaList {
    return RestBatchUpdateMetaListFromJSONTyped(json, false);
}

export function RestBatchUpdateMetaListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestBatchUpdateMetaList {
    if (json == null) {
        return json;
    }
    return {
        
        'updates': ((json['Updates'] as Array<any>).map(RestMetaUpdateFromJSON)),
    };
}

export function RestBatchUpdateMetaListToJSON(json: any): RestBatchUpdateMetaList {
    return RestBatchUpdateMetaListToJSONTyped(json, false);
}

export function RestBatchUpdateMetaListToJSONTyped(value?: RestBatchUpdateMetaList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Updates': ((value['updates'] as Array<any>).map(RestMetaUpdateToJSON)),
    };
}

