/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestTemplate } from './RestTemplate';
import {
    RestTemplateFromJSON,
    RestTemplateFromJSONTyped,
    RestTemplateToJSON,
    RestTemplateToJSONTyped,
} from './RestTemplate';

/**
 * 
 * @export
 * @interface RestListTemplatesResponse
 */
export interface RestListTemplatesResponse {
    /**
     * 
     * @type {Array<RestTemplate>}
     * @memberof RestListTemplatesResponse
     */
    templates?: Array<RestTemplate>;
}

/**
 * Check if a given object implements the RestListTemplatesResponse interface.
 */
export function instanceOfRestListTemplatesResponse(value: object): value is RestListTemplatesResponse {
    return true;
}

export function RestListTemplatesResponseFromJSON(json: any): RestListTemplatesResponse {
    return RestListTemplatesResponseFromJSONTyped(json, false);
}

export function RestListTemplatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestListTemplatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'templates': json['Templates'] == null ? undefined : ((json['Templates'] as Array<any>).map(RestTemplateFromJSON)),
    };
}

export function RestListTemplatesResponseToJSON(json: any): RestListTemplatesResponse {
    return RestListTemplatesResponseToJSONTyped(json, false);
}

export function RestListTemplatesResponseToJSONTyped(value?: RestListTemplatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Templates': value['templates'] == null ? undefined : ((value['templates'] as Array<any>).map(RestTemplateToJSON)),
    };
}

