/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestLockInfo
 */
export interface RestLockInfo {
    /**
     * 
     * @type {boolean}
     * @memberof RestLockInfo
     */
    isLocked?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RestLockInfo
     */
    owner?: string;
}

/**
 * Check if a given object implements the RestLockInfo interface.
 */
export function instanceOfRestLockInfo(value: object): value is RestLockInfo {
    return true;
}

export function RestLockInfoFromJSON(json: any): RestLockInfo {
    return RestLockInfoFromJSONTyped(json, false);
}

export function RestLockInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestLockInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'isLocked': json['IsLocked'] == null ? undefined : json['IsLocked'],
        'owner': json['Owner'] == null ? undefined : json['Owner'],
    };
}

export function RestLockInfoToJSON(json: any): RestLockInfo {
    return RestLockInfoToJSONTyped(json, false);
}

export function RestLockInfoToJSONTyped(value?: RestLockInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'IsLocked': value['isLocked'],
        'Owner': value['owner'],
    };
}

