/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestShareLink } from './RestShareLink';
import {
    RestShareLinkFromJSON,
    RestShareLinkFromJSONTyped,
    RestShareLinkToJSON,
    RestShareLinkToJSONTyped,
} from './RestShareLink';

/**
 * 
 * @export
 * @interface RestUpsertPublicLinkRequest
 */
export interface RestUpsertPublicLinkRequest {
    /**
     * 
     * @type {string}
     * @memberof RestUpsertPublicLinkRequest
     */
    createPassword?: string;
    /**
     * 
     * @type {RestShareLink}
     * @memberof RestUpsertPublicLinkRequest
     */
    link?: RestShareLink;
    /**
     * 
     * @type {boolean}
     * @memberof RestUpsertPublicLinkRequest
     */
    passwordEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RestUpsertPublicLinkRequest
     */
    updateCustomHash?: string;
    /**
     * 
     * @type {string}
     * @memberof RestUpsertPublicLinkRequest
     */
    updatePassword?: string;
    /**
     * 
     * @type {string}
     * @memberof RestUpsertPublicLinkRequest
     */
    uuid?: string;
}

/**
 * Check if a given object implements the RestUpsertPublicLinkRequest interface.
 */
export function instanceOfRestUpsertPublicLinkRequest(value: object): value is RestUpsertPublicLinkRequest {
    return true;
}

export function RestUpsertPublicLinkRequestFromJSON(json: any): RestUpsertPublicLinkRequest {
    return RestUpsertPublicLinkRequestFromJSONTyped(json, false);
}

export function RestUpsertPublicLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestUpsertPublicLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'createPassword': json['CreatePassword'] == null ? undefined : json['CreatePassword'],
        'link': json['Link'] == null ? undefined : RestShareLinkFromJSON(json['Link']),
        'passwordEnabled': json['PasswordEnabled'] == null ? undefined : json['PasswordEnabled'],
        'updateCustomHash': json['UpdateCustomHash'] == null ? undefined : json['UpdateCustomHash'],
        'updatePassword': json['UpdatePassword'] == null ? undefined : json['UpdatePassword'],
        'uuid': json['Uuid'] == null ? undefined : json['Uuid'],
    };
}

export function RestUpsertPublicLinkRequestToJSON(json: any): RestUpsertPublicLinkRequest {
    return RestUpsertPublicLinkRequestToJSONTyped(json, false);
}

export function RestUpsertPublicLinkRequestToJSONTyped(value?: RestUpsertPublicLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'CreatePassword': value['createPassword'],
        'Link': RestShareLinkToJSON(value['link']),
        'PasswordEnabled': value['passwordEnabled'],
        'UpdateCustomHash': value['updateCustomHash'],
        'UpdatePassword': value['updatePassword'],
        'Uuid': value['uuid'],
    };
}

