/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestRevisionMeta
 */
export interface RestRevisionMeta {
    /**
     * 
     * @type {string}
     * @memberof RestRevisionMeta
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RestRevisionMeta
     */
    uuid?: string;
}

/**
 * Check if a given object implements the RestRevisionMeta interface.
 */
export function instanceOfRestRevisionMeta(value: object): value is RestRevisionMeta {
    return true;
}

export function RestRevisionMetaFromJSON(json: any): RestRevisionMeta {
    return RestRevisionMetaFromJSONTyped(json, false);
}

export function RestRevisionMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestRevisionMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['Description'] == null ? undefined : json['Description'],
        'uuid': json['Uuid'] == null ? undefined : json['Uuid'],
    };
}

export function RestRevisionMetaToJSON(json: any): RestRevisionMeta {
    return RestRevisionMetaToJSONTyped(json, false);
}

export function RestRevisionMetaToJSONTyped(value?: RestRevisionMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Description': value['description'],
        'Uuid': value['uuid'],
    };
}

