/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServiceOperationType = {
    Or: 'OR',
    And: 'AND'
} as const;
export type ServiceOperationType = typeof ServiceOperationType[keyof typeof ServiceOperationType];


export function instanceOfServiceOperationType(value: any): boolean {
    for (const key in ServiceOperationType) {
        if (Object.prototype.hasOwnProperty.call(ServiceOperationType, key)) {
            if (ServiceOperationType[key as keyof typeof ServiceOperationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ServiceOperationTypeFromJSON(json: any): ServiceOperationType {
    return ServiceOperationTypeFromJSONTyped(json, false);
}

export function ServiceOperationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceOperationType {
    return json as ServiceOperationType;
}

export function ServiceOperationTypeToJSON(value?: ServiceOperationType | null): any {
    return value as any;
}

export function ServiceOperationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ServiceOperationType {
    return value as ServiceOperationType;
}

