/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServiceResourcePolicyAction = {
    Any: 'ANY',
    Owner: 'OWNER',
    Read: 'READ',
    Write: 'WRITE',
    EditRules: 'EDIT_RULES'
} as const;
export type ServiceResourcePolicyAction = typeof ServiceResourcePolicyAction[keyof typeof ServiceResourcePolicyAction];


export function instanceOfServiceResourcePolicyAction(value: any): boolean {
    for (const key in ServiceResourcePolicyAction) {
        if (Object.prototype.hasOwnProperty.call(ServiceResourcePolicyAction, key)) {
            if (ServiceResourcePolicyAction[key as keyof typeof ServiceResourcePolicyAction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ServiceResourcePolicyActionFromJSON(json: any): ServiceResourcePolicyAction {
    return ServiceResourcePolicyActionFromJSONTyped(json, false);
}

export function ServiceResourcePolicyActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceResourcePolicyAction {
    return json as ServiceResourcePolicyAction;
}

export function ServiceResourcePolicyActionToJSON(value?: ServiceResourcePolicyAction | null): any {
    return value as any;
}

export function ServiceResourcePolicyActionToJSONTyped(value: any, ignoreDiscriminator: boolean): ServiceResourcePolicyAction {
    return value as ServiceResourcePolicyAction;
}

