/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TreeNodeChangeEventEventType = {
    Create: 'CREATE',
    Read: 'READ',
    UpdatePath: 'UPDATE_PATH',
    UpdateContent: 'UPDATE_CONTENT',
    UpdateMeta: 'UPDATE_META',
    UpdateUserMeta: 'UPDATE_USER_META',
    Delete: 'DELETE'
} as const;
export type TreeNodeChangeEventEventType = typeof TreeNodeChangeEventEventType[keyof typeof TreeNodeChangeEventEventType];


export function instanceOfTreeNodeChangeEventEventType(value: any): boolean {
    for (const key in TreeNodeChangeEventEventType) {
        if (Object.prototype.hasOwnProperty.call(TreeNodeChangeEventEventType, key)) {
            if (TreeNodeChangeEventEventType[key as keyof typeof TreeNodeChangeEventEventType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TreeNodeChangeEventEventTypeFromJSON(json: any): TreeNodeChangeEventEventType {
    return TreeNodeChangeEventEventTypeFromJSONTyped(json, false);
}

export function TreeNodeChangeEventEventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeNodeChangeEventEventType {
    return json as TreeNodeChangeEventEventType;
}

export function TreeNodeChangeEventEventTypeToJSON(value?: TreeNodeChangeEventEventType | null): any {
    return value as any;
}

export function TreeNodeChangeEventEventTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): TreeNodeChangeEventEventType {
    return value as TreeNodeChangeEventEventType;
}

