/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TreeGeoPoint
 */
export interface TreeGeoPoint {
    /**
     * 
     * @type {number}
     * @memberof TreeGeoPoint
     */
    lat?: number;
    /**
     * 
     * @type {number}
     * @memberof TreeGeoPoint
     */
    lon?: number;
}

/**
 * Check if a given object implements the TreeGeoPoint interface.
 */
export function instanceOfTreeGeoPoint(value: object): value is TreeGeoPoint {
    return true;
}

export function TreeGeoPointFromJSON(json: any): TreeGeoPoint {
    return TreeGeoPointFromJSONTyped(json, false);
}

export function TreeGeoPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeGeoPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'lat': json['Lat'] == null ? undefined : json['Lat'],
        'lon': json['Lon'] == null ? undefined : json['Lon'],
    };
}

export function TreeGeoPointToJSON(json: any): TreeGeoPoint {
    return TreeGeoPointToJSONTyped(json, false);
}

export function TreeGeoPointToJSONTyped(value?: TreeGeoPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Lat': value['lat'],
        'Lon': value['lon'],
    };
}

