/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ActivityObjectType = {
    BaseObject: 'BaseObject',
    Activity: 'Activity',
    Link: 'Link',
    Mention: 'Mention',
    Collection: 'Collection',
    OrderedCollection: 'OrderedCollection',
    CollectionPage: 'CollectionPage',
    OrderedCollectionPage: 'OrderedCollectionPage',
    Application: 'Application',
    Group: 'Group',
    Organization: 'Organization',
    Person: 'Person',
    Service: 'Service',
    Article: 'Article',
    Audio: 'Audio',
    Document: 'Document',
    Event: 'Event',
    Image: 'Image',
    Note: 'Note',
    Page: 'Page',
    Place: 'Place',
    Profile: 'Profile',
    Relationship: 'Relationship',
    Tombstone: 'Tombstone',
    Video: 'Video',
    Accept: 'Accept',
    Add: 'Add',
    Announce: 'Announce',
    Arrive: 'Arrive',
    Block: 'Block',
    Create: 'Create',
    Delete: 'Delete',
    Dislike: 'Dislike',
    Flag: 'Flag',
    Follow: 'Follow',
    Ignore: 'Ignore',
    Invite: 'Invite',
    Join: 'Join',
    Leave: 'Leave',
    Like: 'Like',
    Listen: 'Listen',
    Move: 'Move',
    Offer: 'Offer',
    Question: 'Question',
    Reject: 'Reject',
    Read: 'Read',
    Remove: 'Remove',
    TentativeReject: 'TentativeReject',
    TentativeAccept: 'TentativeAccept',
    Travel: 'Travel',
    Undo: 'Undo',
    Update: 'Update',
    UpdateComment: 'UpdateComment',
    UpdateMeta: 'UpdateMeta',
    View: 'View',
    Workspace: 'Workspace',
    Digest: 'Digest',
    Folder: 'Folder',
    Cell: 'Cell',
    Share: 'Share'
} as const;

export type ActivityObjectType = typeof ActivityObjectType[keyof typeof ActivityObjectType];



