/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RestNode } from './rest-node';

/**
 * Request to create a selection from a list of nodes.
 * @export
 * @interface RestSelection
 */
export interface RestSelection {
    /**
     * 
     * @type {Array<RestNode>}
     * @memberof RestSelection
     */
    'Nodes': Array<RestNode>;
    /**
     * 
     * @type {string}
     * @memberof RestSelection
     */
    'Uuid'?: string;
}

