/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TreeSearchFacet
 */
export interface TreeSearchFacet {
    /**
     * 
     * @type {number}
     * @memberof TreeSearchFacet
     */
    'Count'?: number;
    /**
     * 
     * @type {number}
     * @memberof TreeSearchFacet
     */
    'End'?: number;
    /**
     * 
     * @type {string}
     * @memberof TreeSearchFacet
     */
    'FieldName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeSearchFacet
     */
    'Label'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeSearchFacet
     */
    'Max'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeSearchFacet
     */
    'Min'?: string;
    /**
     * 
     * @type {number}
     * @memberof TreeSearchFacet
     */
    'Start'?: number;
    /**
     * 
     * @type {string}
     * @memberof TreeSearchFacet
     */
    'Term'?: string;
}

