/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActivityObjectType } from './activity-object-type';

/**
 * 
 * @export
 * @interface ActivityObject
 */
export interface ActivityObject {
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    '@context'?: string;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    'accuracy'?: number;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'actor'?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    'altitude'?: number;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'anyOf'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'attachment'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'attributedTo'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'audience'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'bcc'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'bto'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'cc'?: ActivityObject;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'closed'?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'content'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'current'?: ActivityObject;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'deleted'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'duration'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'endTime'?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'first'?: ActivityObject;
    /**
     * 
     * @type {ActivityObjectType}
     * @memberof ActivityObject
     */
    'formerType'?: ActivityObjectType;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'generator'?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    'height'?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'href'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'hreflang'?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'icon'?: ActivityObject;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'id'?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'image'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'inReplyTo'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'instrument'?: ActivityObject;
    /**
     * 
     * @type {Array<ActivityObject>}
     * @memberof ActivityObject
     */
    'items'?: Array<ActivityObject>;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'last'?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    'latitude'?: number;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'location'?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    'longitude'?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'markdown'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'mediaType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'name'?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'next'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'object'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'oneOf'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'origin'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'partOf'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'prev'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'preview'?: ActivityObject;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'published'?: string;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    'radius'?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'rel'?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'relationship'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'replies'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'result'?: ActivityObject;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'startTime'?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'subject'?: ActivityObject;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'summary'?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'tag'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'target'?: ActivityObject;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'to'?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    'totalItems'?: number;
    /**
     * 
     * @type {ActivityObjectType}
     * @memberof ActivityObject
     */
    'type'?: ActivityObjectType;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'units'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityObject
     */
    'updated'?: string;
    /**
     * 
     * @type {ActivityObject}
     * @memberof ActivityObject
     */
    'url'?: ActivityObject;
    /**
     * 
     * @type {number}
     * @memberof ActivityObject
     */
    'width'?: number;
}



