/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdmACLAction
 */
export interface IdmACLAction {
    /**
     * 
     * @type {string}
     * @memberof IdmACLAction
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IdmACLAction
     */
    value?: string;
}

/**
 * Check if a given object implements the IdmACLAction interface.
 */
export function instanceOfIdmACLAction(value: object): value is IdmACLAction {
    return true;
}

export function IdmACLActionFromJSON(json: any): IdmACLAction {
    return IdmACLActionFromJSONTyped(json, false);
}

export function IdmACLActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdmACLAction {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['Name'] == null ? undefined : json['Name'],
        'value': json['Value'] == null ? undefined : json['Value'],
    };
}

export function IdmACLActionToJSON(json: any): IdmACLAction {
    return IdmACLActionToJSONTyped(json, false);
}

export function IdmACLActionToJSONTyped(value?: IdmACLAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Name': value['name'],
        'Value': value['value'],
    };
}

