/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const IdmWorkspaceScope = {
    Any: 'ANY',
    Admin: 'ADMIN',
    Room: 'ROOM',
    Link: 'LINK'
} as const;
export type IdmWorkspaceScope = typeof IdmWorkspaceScope[keyof typeof IdmWorkspaceScope];


export function instanceOfIdmWorkspaceScope(value: any): boolean {
    for (const key in IdmWorkspaceScope) {
        if (Object.prototype.hasOwnProperty.call(IdmWorkspaceScope, key)) {
            if (IdmWorkspaceScope[key as keyof typeof IdmWorkspaceScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IdmWorkspaceScopeFromJSON(json: any): IdmWorkspaceScope {
    return IdmWorkspaceScopeFromJSONTyped(json, false);
}

export function IdmWorkspaceScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdmWorkspaceScope {
    return json as IdmWorkspaceScope;
}

export function IdmWorkspaceScopeToJSON(value?: IdmWorkspaceScope | null): any {
    return value as any;
}

export function IdmWorkspaceScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): IdmWorkspaceScope {
    return value as IdmWorkspaceScope;
}

