/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const JobsTaskStatus = {
    Unknown: 'Unknown',
    Idle: 'Idle',
    Running: 'Running',
    Finished: 'Finished',
    Interrupted: 'Interrupted',
    Paused: 'Paused',
    Any: 'Any',
    Error: 'Error',
    Queued: 'Queued'
} as const;

export type JobsTaskStatus = typeof JobsTaskStatus[keyof typeof JobsTaskStatus];



