/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobsSelectorRange } from './JobsSelectorRange';
import {
    JobsSelectorRangeFromJSON,
    JobsSelectorRangeFromJSONTyped,
    JobsSelectorRangeToJSON,
    JobsSelectorRangeToJSONTyped,
} from './JobsSelectorRange';
import type { JobsIdmSelectorType } from './JobsIdmSelectorType';
import {
    JobsIdmSelectorTypeFromJSON,
    JobsIdmSelectorTypeFromJSONTyped,
    JobsIdmSelectorTypeToJSON,
    JobsIdmSelectorTypeToJSONTyped,
} from './JobsIdmSelectorType';
import type { ServiceQuery } from './ServiceQuery';
import {
    ServiceQueryFromJSON,
    ServiceQueryFromJSONTyped,
    ServiceQueryToJSON,
    ServiceQueryToJSONTyped,
} from './ServiceQuery';

/**
 * 
 * @export
 * @interface JobsIdmSelector
 */
export interface JobsIdmSelector {
    /**
     * 
     * @type {boolean}
     * @memberof JobsIdmSelector
     */
    all?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JobsIdmSelector
     */
    clearInput?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JobsIdmSelector
     */
    collect?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobsIdmSelector
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof JobsIdmSelector
     */
    fanOutInput?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobsIdmSelector
     */
    label?: string;
    /**
     * 
     * @type {ServiceQuery}
     * @memberof JobsIdmSelector
     */
    query?: ServiceQuery;
    /**
     * 
     * @type {JobsSelectorRange}
     * @memberof JobsIdmSelector
     */
    range?: JobsSelectorRange;
    /**
     * 
     * @type {string}
     * @memberof JobsIdmSelector
     */
    timeout?: string;
    /**
     * 
     * @type {JobsIdmSelectorType}
     * @memberof JobsIdmSelector
     */
    type?: JobsIdmSelectorType;
}



/**
 * Check if a given object implements the JobsIdmSelector interface.
 */
export function instanceOfJobsIdmSelector(value: object): value is JobsIdmSelector {
    return true;
}

export function JobsIdmSelectorFromJSON(json: any): JobsIdmSelector {
    return JobsIdmSelectorFromJSONTyped(json, false);
}

export function JobsIdmSelectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsIdmSelector {
    if (json == null) {
        return json;
    }
    return {
        
        'all': json['All'] == null ? undefined : json['All'],
        'clearInput': json['ClearInput'] == null ? undefined : json['ClearInput'],
        'collect': json['Collect'] == null ? undefined : json['Collect'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'fanOutInput': json['FanOutInput'] == null ? undefined : json['FanOutInput'],
        'label': json['Label'] == null ? undefined : json['Label'],
        'query': json['Query'] == null ? undefined : ServiceQueryFromJSON(json['Query']),
        'range': json['Range'] == null ? undefined : JobsSelectorRangeFromJSON(json['Range']),
        'timeout': json['Timeout'] == null ? undefined : json['Timeout'],
        'type': json['Type'] == null ? undefined : JobsIdmSelectorTypeFromJSON(json['Type']),
    };
}

export function JobsIdmSelectorToJSON(json: any): JobsIdmSelector {
    return JobsIdmSelectorToJSONTyped(json, false);
}

export function JobsIdmSelectorToJSONTyped(value?: JobsIdmSelector | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'All': value['all'],
        'ClearInput': value['clearInput'],
        'Collect': value['collect'],
        'Description': value['description'],
        'FanOutInput': value['fanOutInput'],
        'Label': value['label'],
        'Query': ServiceQueryToJSON(value['query']),
        'Range': JobsSelectorRangeToJSON(value['range']),
        'Timeout': value['timeout'],
        'Type': JobsIdmSelectorTypeToJSON(value['type']),
    };
}

