/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobsCommand } from './jobs-command';

/**
 * 
 * @export
 * @interface JobsCtrlCommand
 */
export interface JobsCtrlCommand {
    /**
     * 
     * @type {JobsCommand}
     * @memberof JobsCtrlCommand
     */
    'Cmd'?: JobsCommand;
    /**
     * 
     * @type {string}
     * @memberof JobsCtrlCommand
     */
    'JobId'?: string;
    /**
     * 
     * @type {string}
     * @memberof JobsCtrlCommand
     */
    'OwnerId'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof JobsCtrlCommand
     */
    'RunParameters'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof JobsCtrlCommand
     */
    'TaskId'?: string;
}



