/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobsDataSourceSelectorType } from './JobsDataSourceSelectorType';
import {
    JobsDataSourceSelectorTypeFromJSON,
    JobsDataSourceSelectorTypeFromJSONTyped,
    JobsDataSourceSelectorTypeToJSON,
    JobsDataSourceSelectorTypeToJSONTyped,
} from './JobsDataSourceSelectorType';
import type { ServiceQuery } from './ServiceQuery';
import {
    ServiceQueryFromJSON,
    ServiceQueryFromJSONTyped,
    ServiceQueryToJSON,
    ServiceQueryToJSONTyped,
} from './ServiceQuery';

/**
 * 
 * @export
 * @interface JobsDataSourceSelector
 */
export interface JobsDataSourceSelector {
    /**
     * 
     * @type {boolean}
     * @memberof JobsDataSourceSelector
     */
    all?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JobsDataSourceSelector
     */
    clearInput?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JobsDataSourceSelector
     */
    collect?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobsDataSourceSelector
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof JobsDataSourceSelector
     */
    fanOutInput?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobsDataSourceSelector
     */
    label?: string;
    /**
     * 
     * @type {ServiceQuery}
     * @memberof JobsDataSourceSelector
     */
    query?: ServiceQuery;
    /**
     * 
     * @type {string}
     * @memberof JobsDataSourceSelector
     */
    timeout?: string;
    /**
     * 
     * @type {JobsDataSourceSelectorType}
     * @memberof JobsDataSourceSelector
     */
    type?: JobsDataSourceSelectorType;
}



/**
 * Check if a given object implements the JobsDataSourceSelector interface.
 */
export function instanceOfJobsDataSourceSelector(value: object): value is JobsDataSourceSelector {
    return true;
}

export function JobsDataSourceSelectorFromJSON(json: any): JobsDataSourceSelector {
    return JobsDataSourceSelectorFromJSONTyped(json, false);
}

export function JobsDataSourceSelectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsDataSourceSelector {
    if (json == null) {
        return json;
    }
    return {
        
        'all': json['All'] == null ? undefined : json['All'],
        'clearInput': json['ClearInput'] == null ? undefined : json['ClearInput'],
        'collect': json['Collect'] == null ? undefined : json['Collect'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'fanOutInput': json['FanOutInput'] == null ? undefined : json['FanOutInput'],
        'label': json['Label'] == null ? undefined : json['Label'],
        'query': json['Query'] == null ? undefined : ServiceQueryFromJSON(json['Query']),
        'timeout': json['Timeout'] == null ? undefined : json['Timeout'],
        'type': json['Type'] == null ? undefined : JobsDataSourceSelectorTypeFromJSON(json['Type']),
    };
}

export function JobsDataSourceSelectorToJSON(json: any): JobsDataSourceSelector {
    return JobsDataSourceSelectorToJSONTyped(json, false);
}

export function JobsDataSourceSelectorToJSONTyped(value?: JobsDataSourceSelector | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'All': value['all'],
        'ClearInput': value['clearInput'],
        'Collect': value['collect'],
        'Description': value['description'],
        'FanOutInput': value['fanOutInput'],
        'Label': value['label'],
        'Query': ServiceQueryToJSON(value['query']),
        'Timeout': value['timeout'],
        'Type': JobsDataSourceSelectorTypeToJSON(value['type']),
    };
}

