/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobsContextMetaFilterType = {
    RequestMeta: 'RequestMeta',
    ContextUser: 'ContextUser'
} as const;
export type JobsContextMetaFilterType = typeof JobsContextMetaFilterType[keyof typeof JobsContextMetaFilterType];


export function instanceOfJobsContextMetaFilterType(value: any): boolean {
    for (const key in JobsContextMetaFilterType) {
        if (Object.prototype.hasOwnProperty.call(JobsContextMetaFilterType, key)) {
            if (JobsContextMetaFilterType[key as keyof typeof JobsContextMetaFilterType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobsContextMetaFilterTypeFromJSON(json: any): JobsContextMetaFilterType {
    return JobsContextMetaFilterTypeFromJSONTyped(json, false);
}

export function JobsContextMetaFilterTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsContextMetaFilterType {
    return json as JobsContextMetaFilterType;
}

export function JobsContextMetaFilterTypeToJSON(value?: JobsContextMetaFilterType | null): any {
    return value as any;
}

export function JobsContextMetaFilterTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): JobsContextMetaFilterType {
    return value as JobsContextMetaFilterType;
}

