/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobsTaskStatus = {
    Unknown: 'Unknown',
    Idle: 'Idle',
    Running: 'Running',
    Finished: 'Finished',
    Interrupted: 'Interrupted',
    Paused: 'Paused',
    Any: 'Any',
    Error: 'Error',
    Queued: 'Queued'
} as const;
export type JobsTaskStatus = typeof JobsTaskStatus[keyof typeof JobsTaskStatus];


export function instanceOfJobsTaskStatus(value: any): boolean {
    for (const key in JobsTaskStatus) {
        if (Object.prototype.hasOwnProperty.call(JobsTaskStatus, key)) {
            if (JobsTaskStatus[key as keyof typeof JobsTaskStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobsTaskStatusFromJSON(json: any): JobsTaskStatus {
    return JobsTaskStatusFromJSONTyped(json, false);
}

export function JobsTaskStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsTaskStatus {
    return json as JobsTaskStatus;
}

export function JobsTaskStatusToJSON(value?: JobsTaskStatus | null): any {
    return value as any;
}

export function JobsTaskStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): JobsTaskStatus {
    return value as JobsTaskStatus;
}

