/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceResourcePolicy } from './ServiceResourcePolicy';
import {
    ServiceResourcePolicyFromJSON,
    ServiceResourcePolicyFromJSONTyped,
    ServiceResourcePolicyToJSON,
    ServiceResourcePolicyToJSONTyped,
} from './ServiceResourcePolicy';

/**
 * 
 * @export
 * @interface JobsJobHook
 */
export interface JobsJobHook {
    /**
     * 
     * @type {boolean}
     * @memberof JobsJobHook
     */
    allowOverridePresets?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobsJobHook
     */
    apiSlug?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof JobsJobHook
     */
    metadata?: { [key: string]: string; };
    /**
     * 
     * @type {Array<ServiceResourcePolicy>}
     * @memberof JobsJobHook
     */
    policies?: Array<ServiceResourcePolicy>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof JobsJobHook
     */
    presetParameters?: { [key: string]: string; };
}

/**
 * Check if a given object implements the JobsJobHook interface.
 */
export function instanceOfJobsJobHook(value: object): value is JobsJobHook {
    return true;
}

export function JobsJobHookFromJSON(json: any): JobsJobHook {
    return JobsJobHookFromJSONTyped(json, false);
}

export function JobsJobHookFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsJobHook {
    if (json == null) {
        return json;
    }
    return {
        
        'allowOverridePresets': json['AllowOverridePresets'] == null ? undefined : json['AllowOverridePresets'],
        'apiSlug': json['ApiSlug'] == null ? undefined : json['ApiSlug'],
        'metadata': json['Metadata'] == null ? undefined : json['Metadata'],
        'policies': json['Policies'] == null ? undefined : ((json['Policies'] as Array<any>).map(ServiceResourcePolicyFromJSON)),
        'presetParameters': json['PresetParameters'] == null ? undefined : json['PresetParameters'],
    };
}

export function JobsJobHookToJSON(json: any): JobsJobHook {
    return JobsJobHookToJSONTyped(json, false);
}

export function JobsJobHookToJSONTyped(value?: JobsJobHook | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AllowOverridePresets': value['allowOverridePresets'],
        'ApiSlug': value['apiSlug'],
        'Metadata': value['metadata'],
        'Policies': value['policies'] == null ? undefined : ((value['policies'] as Array<any>).map(ServiceResourcePolicyToJSON)),
        'PresetParameters': value['presetParameters'],
    };
}

