/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobsContextMetaFilterType } from './JobsContextMetaFilterType';
import {
    JobsContextMetaFilterTypeFromJSON,
    JobsContextMetaFilterTypeFromJSONTyped,
    JobsContextMetaFilterTypeToJSON,
    JobsContextMetaFilterTypeToJSONTyped,
} from './JobsContextMetaFilterType';
import type { ServiceQuery } from './ServiceQuery';
import {
    ServiceQueryFromJSON,
    ServiceQueryFromJSONTyped,
    ServiceQueryToJSON,
    ServiceQueryToJSONTyped,
} from './ServiceQuery';

/**
 * 
 * @export
 * @interface JobsContextMetaFilter
 */
export interface JobsContextMetaFilter {
    /**
     * 
     * @type {string}
     * @memberof JobsContextMetaFilter
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof JobsContextMetaFilter
     */
    label?: string;
    /**
     * 
     * @type {ServiceQuery}
     * @memberof JobsContextMetaFilter
     */
    query?: ServiceQuery;
    /**
     * 
     * @type {JobsContextMetaFilterType}
     * @memberof JobsContextMetaFilter
     */
    type?: JobsContextMetaFilterType;
}



/**
 * Check if a given object implements the JobsContextMetaFilter interface.
 */
export function instanceOfJobsContextMetaFilter(value: object): value is JobsContextMetaFilter {
    return true;
}

export function JobsContextMetaFilterFromJSON(json: any): JobsContextMetaFilter {
    return JobsContextMetaFilterFromJSONTyped(json, false);
}

export function JobsContextMetaFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsContextMetaFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['Description'] == null ? undefined : json['Description'],
        'label': json['Label'] == null ? undefined : json['Label'],
        'query': json['Query'] == null ? undefined : ServiceQueryFromJSON(json['Query']),
        'type': json['Type'] == null ? undefined : JobsContextMetaFilterTypeFromJSON(json['Type']),
    };
}

export function JobsContextMetaFilterToJSON(json: any): JobsContextMetaFilter {
    return JobsContextMetaFilterToJSONTyped(json, false);
}

export function JobsContextMetaFilterToJSONTyped(value?: JobsContextMetaFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Description': value['description'],
        'Label': value['label'],
        'Query': ServiceQueryToJSON(value['query']),
        'Type': JobsContextMetaFilterTypeToJSON(value['type']),
    };
}

