/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobsSelectorRange
 */
export interface JobsSelectorRange {
    /**
     * 
     * @type {string}
     * @memberof JobsSelectorRange
     */
    limit?: string;
    /**
     * 
     * @type {string}
     * @memberof JobsSelectorRange
     */
    offset?: string;
    /**
     * 
     * @type {string}
     * @memberof JobsSelectorRange
     */
    orderBy?: string;
    /**
     * 
     * @type {string}
     * @memberof JobsSelectorRange
     */
    orderDir?: string;
}

/**
 * Check if a given object implements the JobsSelectorRange interface.
 */
export function instanceOfJobsSelectorRange(value: object): value is JobsSelectorRange {
    return true;
}

export function JobsSelectorRangeFromJSON(json: any): JobsSelectorRange {
    return JobsSelectorRangeFromJSONTyped(json, false);
}

export function JobsSelectorRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsSelectorRange {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['Limit'] == null ? undefined : json['Limit'],
        'offset': json['Offset'] == null ? undefined : json['Offset'],
        'orderBy': json['OrderBy'] == null ? undefined : json['OrderBy'],
        'orderDir': json['OrderDir'] == null ? undefined : json['OrderDir'],
    };
}

export function JobsSelectorRangeToJSON(json: any): JobsSelectorRange {
    return JobsSelectorRangeToJSONTyped(json, false);
}

export function JobsSelectorRangeToJSONTyped(value?: JobsSelectorRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Limit': value['limit'],
        'Offset': value['offset'],
        'OrderBy': value['orderBy'],
        'OrderDir': value['orderDir'],
    };
}

