/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobsSchedule
 */
export interface JobsSchedule {
    /**
     * 
     * @type {string}
     * @memberof JobsSchedule
     */
    iso8601MinDelta?: string;
    /**
     * ISO 8601 Description of the scheduling for instance "R2/2015-06-04T19:25:16.828696-07:00/PT4S"
     * where first part is the number of repetitions (if 0, infinite repetition), 
     * second part the starting date and last part, the duration between 2 occurrences.
     * @type {string}
     * @memberof JobsSchedule
     */
    iso8601Schedule?: string;
}

/**
 * Check if a given object implements the JobsSchedule interface.
 */
export function instanceOfJobsSchedule(value: object): value is JobsSchedule {
    return true;
}

export function JobsScheduleFromJSON(json: any): JobsSchedule {
    return JobsScheduleFromJSONTyped(json, false);
}

export function JobsScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsSchedule {
    if (json == null) {
        return json;
    }
    return {
        
        'iso8601MinDelta': json['Iso8601MinDelta'] == null ? undefined : json['Iso8601MinDelta'],
        'iso8601Schedule': json['Iso8601Schedule'] == null ? undefined : json['Iso8601Schedule'],
    };
}

export function JobsScheduleToJSON(json: any): JobsSchedule {
    return JobsScheduleToJSONTyped(json, false);
}

export function JobsScheduleToJSONTyped(value?: JobsSchedule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Iso8601MinDelta': value['iso8601MinDelta'],
        'Iso8601Schedule': value['iso8601Schedule'],
    };
}

