/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobsIdmSelectorType = {
    User: 'User',
    Role: 'Role',
    Workspace: 'Workspace',
    Acl: 'Acl'
} as const;
export type JobsIdmSelectorType = typeof JobsIdmSelectorType[keyof typeof JobsIdmSelectorType];


export function instanceOfJobsIdmSelectorType(value: any): boolean {
    for (const key in JobsIdmSelectorType) {
        if (Object.prototype.hasOwnProperty.call(JobsIdmSelectorType, key)) {
            if (JobsIdmSelectorType[key as keyof typeof JobsIdmSelectorType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobsIdmSelectorTypeFromJSON(json: any): JobsIdmSelectorType {
    return JobsIdmSelectorTypeFromJSONTyped(json, false);
}

export function JobsIdmSelectorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsIdmSelectorType {
    return json as JobsIdmSelectorType;
}

export function JobsIdmSelectorTypeToJSON(value?: JobsIdmSelectorType | null): any {
    return value as any;
}

export function JobsIdmSelectorTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): JobsIdmSelectorType {
    return value as JobsIdmSelectorType;
}

