/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobsJobParameter
 */
export interface JobsJobParameter {
    /**
     * 
     * @type {string}
     * @memberof JobsJobParameter
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof JobsJobParameter
     */
    jsonChoices?: string;
    /**
     * 
     * @type {boolean}
     * @memberof JobsJobParameter
     */
    mandatory?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobsJobParameter
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof JobsJobParameter
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof JobsJobParameter
     */
    value?: string;
}

/**
 * Check if a given object implements the JobsJobParameter interface.
 */
export function instanceOfJobsJobParameter(value: object): value is JobsJobParameter {
    return true;
}

export function JobsJobParameterFromJSON(json: any): JobsJobParameter {
    return JobsJobParameterFromJSONTyped(json, false);
}

export function JobsJobParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsJobParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['Description'] == null ? undefined : json['Description'],
        'jsonChoices': json['JsonChoices'] == null ? undefined : json['JsonChoices'],
        'mandatory': json['Mandatory'] == null ? undefined : json['Mandatory'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'type': json['Type'] == null ? undefined : json['Type'],
        'value': json['Value'] == null ? undefined : json['Value'],
    };
}

export function JobsJobParameterToJSON(json: any): JobsJobParameter {
    return JobsJobParameterToJSONTyped(json, false);
}

export function JobsJobParameterToJSONTyped(value?: JobsJobParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Description': value['description'],
        'JsonChoices': value['jsonChoices'],
        'Mandatory': value['mandatory'],
        'Name': value['name'],
        'Type': value['type'],
        'Value': value['value'],
    };
}

