/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StatusFilterDeletedStatus } from './status-filter-deleted-status';
// May contain unused imports in some cases
// @ts-ignore
import type { StatusFilterDraftStatus } from './status-filter-draft-status';

/**
 * 
 * @export
 * @interface LookupFilterStatusFilter
 */
export interface LookupFilterStatusFilter {
    /**
     * 
     * @type {StatusFilterDeletedStatus}
     * @memberof LookupFilterStatusFilter
     */
    'Deleted'?: StatusFilterDeletedStatus;
    /**
     * 
     * @type {StatusFilterDraftStatus}
     * @memberof LookupFilterStatusFilter
     */
    'Draft'?: StatusFilterDraftStatus;
    /**
     * 
     * @type {boolean}
     * @memberof LookupFilterStatusFilter
     */
    'HasPublicLink'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LookupFilterStatusFilter
     */
    'IsBookmarked'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LookupFilterStatusFilter
     */
    'IsDraft'?: boolean;
}



