/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestShareLinkTargetUser
 */
export interface RestShareLinkTargetUser {
    /**
     * 
     * @type {string}
     * @memberof RestShareLinkTargetUser
     */
    display?: string;
    /**
     * 
     * @type {number}
     * @memberof RestShareLinkTargetUser
     */
    downloadCount?: number;
}

/**
 * Check if a given object implements the RestShareLinkTargetUser interface.
 */
export function instanceOfRestShareLinkTargetUser(value: object): value is RestShareLinkTargetUser {
    return true;
}

export function RestShareLinkTargetUserFromJSON(json: any): RestShareLinkTargetUser {
    return RestShareLinkTargetUserFromJSONTyped(json, false);
}

export function RestShareLinkTargetUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestShareLinkTargetUser {
    if (json == null) {
        return json;
    }
    return {
        
        'display': json['Display'] == null ? undefined : json['Display'],
        'downloadCount': json['DownloadCount'] == null ? undefined : json['DownloadCount'],
    };
}

export function RestShareLinkTargetUserToJSON(json: any): RestShareLinkTargetUser {
    return RestShareLinkTargetUserToJSONTyped(json, false);
}

export function RestShareLinkTargetUserToJSONTyped(value?: RestShareLinkTargetUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Display': value['display'],
        'DownloadCount': value['downloadCount'],
    };
}

