/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RestVersionMeta
 */
export interface RestVersionMeta {
    /**
     * 
     * @type {string}
     * @memberof RestVersionMeta
     */
    'Description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RestVersionMeta
     */
    'IsDraft'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RestVersionMeta
     */
    'IsHead'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RestVersionMeta
     */
    'OwnerUuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestVersionMeta
     */
    'VersionId': string;
}

