/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestError
 */
export interface RestError {
    /**
     * 
     * @type {string}
     * @memberof RestError
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof RestError
     */
    detail?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RestError
     */
    meta?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof RestError
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof RestError
     */
    title?: string;
}

/**
 * Check if a given object implements the RestError interface.
 */
export function instanceOfRestError(value: object): value is RestError {
    return true;
}

export function RestErrorFromJSON(json: any): RestError {
    return RestErrorFromJSONTyped(json, false);
}

export function RestErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['Code'] == null ? undefined : json['Code'],
        'detail': json['Detail'] == null ? undefined : json['Detail'],
        'meta': json['Meta'] == null ? undefined : json['Meta'],
        'source': json['Source'] == null ? undefined : json['Source'],
        'title': json['Title'] == null ? undefined : json['Title'],
    };
}

export function RestErrorToJSON(json: any): RestError {
    return RestErrorToJSONTyped(json, false);
}

export function RestErrorToJSONTyped(value?: RestError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Code': value['code'],
        'Detail': value['detail'],
        'Meta': value['meta'],
        'Source': value['source'],
        'Title': value['title'],
    };
}

