/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RestPublicLinkDeleteSuccess
 */
export interface RestPublicLinkDeleteSuccess {
    /**
     * 
     * @type {string}
     * @memberof RestPublicLinkDeleteSuccess
     */
    'Message'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestPublicLinkDeleteSuccess
     */
    'Uuid'?: string;
}

