/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestBackgroundJobResult
 */
export interface RestBackgroundJobResult {
    /**
     * 
     * @type {string}
     * @memberof RestBackgroundJobResult
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof RestBackgroundJobResult
     */
    nodeUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof RestBackgroundJobResult
     */
    uuid?: string;
}

/**
 * Check if a given object implements the RestBackgroundJobResult interface.
 */
export function instanceOfRestBackgroundJobResult(value: object): value is RestBackgroundJobResult {
    return true;
}

export function RestBackgroundJobResultFromJSON(json: any): RestBackgroundJobResult {
    return RestBackgroundJobResultFromJSONTyped(json, false);
}

export function RestBackgroundJobResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestBackgroundJobResult {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['Label'] == null ? undefined : json['Label'],
        'nodeUuid': json['NodeUuid'] == null ? undefined : json['NodeUuid'],
        'uuid': json['Uuid'] == null ? undefined : json['Uuid'],
    };
}

export function RestBackgroundJobResultToJSON(json: any): RestBackgroundJobResult {
    return RestBackgroundJobResultToJSONTyped(json, false);
}

export function RestBackgroundJobResultToJSONTyped(value?: RestBackgroundJobResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Label': value['label'],
        'NodeUuid': value['nodeUuid'],
        'Uuid': value['uuid'],
    };
}

