/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestJsonMeta
 */
export interface RestJsonMeta {
    /**
     * 
     * @type {string}
     * @memberof RestJsonMeta
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof RestJsonMeta
     */
    value?: string;
}

/**
 * Check if a given object implements the RestJsonMeta interface.
 */
export function instanceOfRestJsonMeta(value: object): value is RestJsonMeta {
    return true;
}

export function RestJsonMetaFromJSON(json: any): RestJsonMeta {
    return RestJsonMetaFromJSONTyped(json, false);
}

export function RestJsonMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestJsonMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'namespace': json['Namespace'] == null ? undefined : json['Namespace'],
        'value': json['Value'] == null ? undefined : json['Value'],
    };
}

export function RestJsonMetaToJSON(json: any): RestJsonMeta {
    return RestJsonMetaToJSONTyped(json, false);
}

export function RestJsonMetaToJSONTyped(value?: RestJsonMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Namespace': value['namespace'],
        'Value': value['value'],
    };
}

