/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestBackgroundJobResult } from './RestBackgroundJobResult';
import {
    RestBackgroundJobResultFromJSON,
    RestBackgroundJobResultFromJSONTyped,
    RestBackgroundJobResultToJSON,
    RestBackgroundJobResultToJSONTyped,
} from './RestBackgroundJobResult';
import type { RestNode } from './RestNode';
import {
    RestNodeFromJSON,
    RestNodeFromJSONTyped,
    RestNodeToJSON,
    RestNodeToJSONTyped,
} from './RestNode';
import type { RestActionStatus } from './RestActionStatus';
import {
    RestActionStatusFromJSON,
    RestActionStatusFromJSONTyped,
    RestActionStatusToJSON,
    RestActionStatusToJSONTyped,
} from './RestActionStatus';

/**
 * 
 * @export
 * @interface RestActionResponse
 */
export interface RestActionResponse {
    /**
     * 
     * @type {Array<RestNode>}
     * @memberof RestActionResponse
     */
    affectedNodes?: Array<RestNode>;
    /**
     * 
     * @type {Array<RestBackgroundJobResult>}
     * @memberof RestActionResponse
     */
    jobs?: Array<RestBackgroundJobResult>;
    /**
     * 
     * @type {RestActionStatus}
     * @memberof RestActionResponse
     */
    status?: RestActionStatus;
}



/**
 * Check if a given object implements the RestActionResponse interface.
 */
export function instanceOfRestActionResponse(value: object): value is RestActionResponse {
    return true;
}

export function RestActionResponseFromJSON(json: any): RestActionResponse {
    return RestActionResponseFromJSONTyped(json, false);
}

export function RestActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestActionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'affectedNodes': json['AffectedNodes'] == null ? undefined : ((json['AffectedNodes'] as Array<any>).map(RestNodeFromJSON)),
        'jobs': json['Jobs'] == null ? undefined : ((json['Jobs'] as Array<any>).map(RestBackgroundJobResultFromJSON)),
        'status': json['Status'] == null ? undefined : RestActionStatusFromJSON(json['Status']),
    };
}

export function RestActionResponseToJSON(json: any): RestActionResponse {
    return RestActionResponseToJSONTyped(json, false);
}

export function RestActionResponseToJSONTyped(value?: RestActionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AffectedNodes': value['affectedNodes'] == null ? undefined : ((value['affectedNodes'] as Array<any>).map(RestNodeToJSON)),
        'Jobs': value['jobs'] == null ? undefined : ((value['jobs'] as Array<any>).map(RestBackgroundJobResultToJSON)),
        'Status': RestActionStatusToJSON(value['status']),
    };
}

