/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestShareLink } from './RestShareLink';
import {
    RestShareLinkFromJSON,
    RestShareLinkFromJSONTyped,
    RestShareLinkToJSON,
    RestShareLinkToJSONTyped,
} from './RestShareLink';

/**
 * 
 * @export
 * @interface RestPublicLinkRequest
 */
export interface RestPublicLinkRequest {
    /**
     * 
     * @type {string}
     * @memberof RestPublicLinkRequest
     */
    createPassword?: string;
    /**
     * 
     * @type {RestShareLink}
     * @memberof RestPublicLinkRequest
     */
    link?: RestShareLink;
    /**
     * 
     * @type {boolean}
     * @memberof RestPublicLinkRequest
     */
    passwordEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RestPublicLinkRequest
     */
    updateCustomHash?: string;
    /**
     * 
     * @type {string}
     * @memberof RestPublicLinkRequest
     */
    updatePassword?: string;
}

/**
 * Check if a given object implements the RestPublicLinkRequest interface.
 */
export function instanceOfRestPublicLinkRequest(value: object): value is RestPublicLinkRequest {
    return true;
}

export function RestPublicLinkRequestFromJSON(json: any): RestPublicLinkRequest {
    return RestPublicLinkRequestFromJSONTyped(json, false);
}

export function RestPublicLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestPublicLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'createPassword': json['CreatePassword'] == null ? undefined : json['CreatePassword'],
        'link': json['Link'] == null ? undefined : RestShareLinkFromJSON(json['Link']),
        'passwordEnabled': json['PasswordEnabled'] == null ? undefined : json['PasswordEnabled'],
        'updateCustomHash': json['UpdateCustomHash'] == null ? undefined : json['UpdateCustomHash'],
        'updatePassword': json['UpdatePassword'] == null ? undefined : json['UpdatePassword'],
    };
}

export function RestPublicLinkRequestToJSON(json: any): RestPublicLinkRequest {
    return RestPublicLinkRequestToJSONTyped(json, false);
}

export function RestPublicLinkRequestToJSONTyped(value?: RestPublicLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'CreatePassword': value['createPassword'],
        'Link': RestShareLinkToJSON(value['link']),
        'PasswordEnabled': value['passwordEnabled'],
        'UpdateCustomHash': value['updateCustomHash'],
        'UpdatePassword': value['updatePassword'],
    };
}

