/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestIncomingNode } from './RestIncomingNode';
import {
    RestIncomingNodeFromJSON,
    RestIncomingNodeFromJSONTyped,
    RestIncomingNodeToJSON,
    RestIncomingNodeToJSONTyped,
} from './RestIncomingNode';

/**
 * 
 * @export
 * @interface RestCreateRequest
 */
export interface RestCreateRequest {
    /**
     * 
     * @type {Array<RestIncomingNode>}
     * @memberof RestCreateRequest
     */
    inputs?: Array<RestIncomingNode>;
    /**
     * 
     * @type {boolean}
     * @memberof RestCreateRequest
     */
    recursive?: boolean;
}

/**
 * Check if a given object implements the RestCreateRequest interface.
 */
export function instanceOfRestCreateRequest(value: object): value is RestCreateRequest {
    return true;
}

export function RestCreateRequestFromJSON(json: any): RestCreateRequest {
    return RestCreateRequestFromJSONTyped(json, false);
}

export function RestCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'inputs': json['Inputs'] == null ? undefined : ((json['Inputs'] as Array<any>).map(RestIncomingNodeFromJSON)),
        'recursive': json['Recursive'] == null ? undefined : json['Recursive'],
    };
}

export function RestCreateRequestToJSON(json: any): RestCreateRequest {
    return RestCreateRequestToJSONTyped(json, false);
}

export function RestCreateRequestToJSONTyped(value?: RestCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Inputs': value['inputs'] == null ? undefined : ((value['inputs'] as Array<any>).map(RestIncomingNodeToJSON)),
        'Recursive': value['recursive'],
    };
}

