/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RestFilePreview } from './rest-file-preview';
// May contain unused imports in some cases
// @ts-ignore
import type { RestPreSignedURL } from './rest-pre-signed-url';

/**
 * 
 * @export
 * @interface RestVersion
 */
export interface RestVersion {
    /**
     * 
     * @type {string}
     * @memberof RestVersion
     */
    'ContentHash'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestVersion
     */
    'Description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RestVersion
     */
    'Draft'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RestVersion
     */
    'ETag'?: string;
    /**
     * 
     * @type {{ [key: string]: RestPreSignedURL; }}
     * @memberof RestVersion
     */
    'EditorURLs'?: { [key: string]: RestPreSignedURL; };
    /**
     * 
     * @type {Array<RestFilePreview>}
     * @memberof RestVersion
     */
    'FilePreviews'?: Array<RestFilePreview>;
    /**
     * 
     * @type {boolean}
     * @memberof RestVersion
     */
    'IsHead'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RestVersion
     */
    'MTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestVersion
     */
    'OwnerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestVersion
     */
    'OwnerUuid'?: string;
    /**
     * 
     * @type {RestPreSignedURL}
     * @memberof RestVersion
     */
    'PreSignedGET'?: RestPreSignedURL;
    /**
     * 
     * @type {string}
     * @memberof RestVersion
     */
    'Size'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestVersion
     */
    'VersionId': string;
}

