/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IdmUserMetaNamespace } from './idm-user-meta-namespace';

/**
 * 
 * @export
 * @interface RestUserMetaNamespaceCollection
 */
export interface RestUserMetaNamespaceCollection {
    /**
     * 
     * @type {Array<IdmUserMetaNamespace>}
     * @memberof RestUserMetaNamespaceCollection
     */
    'Namespaces'?: Array<IdmUserMetaNamespace>;
}

