/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestNsOp } from './RestNsOp';
import {
    RestNsOpFromJSON,
    RestNsOpFromJSONTyped,
    RestNsOpToJSON,
    RestNsOpToJSONTyped,
} from './RestNsOp';

/**
 * 
 * @export
 * @interface RestNamespaceValuesOperation
 */
export interface RestNamespaceValuesOperation {
    /**
     * 
     * @type {RestNsOp}
     * @memberof RestNamespaceValuesOperation
     */
    operation?: RestNsOp;
    /**
     * 
     * @type {Array<string>}
     * @memberof RestNamespaceValuesOperation
     */
    values?: Array<string>;
}



/**
 * Check if a given object implements the RestNamespaceValuesOperation interface.
 */
export function instanceOfRestNamespaceValuesOperation(value: object): value is RestNamespaceValuesOperation {
    return true;
}

export function RestNamespaceValuesOperationFromJSON(json: any): RestNamespaceValuesOperation {
    return RestNamespaceValuesOperationFromJSONTyped(json, false);
}

export function RestNamespaceValuesOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestNamespaceValuesOperation {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['Operation'] == null ? undefined : RestNsOpFromJSON(json['Operation']),
        'values': json['Values'] == null ? undefined : json['Values'],
    };
}

export function RestNamespaceValuesOperationToJSON(json: any): RestNamespaceValuesOperation {
    return RestNamespaceValuesOperationToJSONTyped(json, false);
}

export function RestNamespaceValuesOperationToJSONTyped(value?: RestNamespaceValuesOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Operation': RestNsOpToJSON(value['operation']),
        'Values': value['values'],
    };
}

