/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LookupFilterDateRange } from './lookup-filter-date-range';
// May contain unused imports in some cases
// @ts-ignore
import type { LookupFilterMetaFilter } from './lookup-filter-meta-filter';
// May contain unused imports in some cases
// @ts-ignore
import type { LookupFilterPathPrefix } from './lookup-filter-path-prefix';
// May contain unused imports in some cases
// @ts-ignore
import type { LookupFilterSizeRange } from './lookup-filter-size-range';
// May contain unused imports in some cases
// @ts-ignore
import type { LookupFilterStatusFilter } from './lookup-filter-status-filter';
// May contain unused imports in some cases
// @ts-ignore
import type { LookupFilterTextSearch } from './lookup-filter-text-search';
// May contain unused imports in some cases
// @ts-ignore
import type { TreeNodeType } from './tree-node-type';

/**
 * 
 * @export
 * @interface RestLookupFilter
 */
export interface RestLookupFilter {
    /**
     * 
     * @type {LookupFilterDateRange}
     * @memberof RestLookupFilter
     */
    'Date'?: LookupFilterDateRange;
    /**
     * 
     * @type {Array<string>}
     * @memberof RestLookupFilter
     */
    'Extensions'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RestLookupFilter
     */
    'FreeExpression'?: string;
    /**
     * 
     * @type {Array<LookupFilterMetaFilter>}
     * @memberof RestLookupFilter
     */
    'Metadata'?: Array<LookupFilterMetaFilter>;
    /**
     * 
     * @type {Array<LookupFilterPathPrefix>}
     * @memberof RestLookupFilter
     */
    'Prefixes'?: Array<LookupFilterPathPrefix>;
    /**
     * 
     * @type {LookupFilterSizeRange}
     * @memberof RestLookupFilter
     */
    'Size'?: LookupFilterSizeRange;
    /**
     * 
     * @type {LookupFilterStatusFilter}
     * @memberof RestLookupFilter
     */
    'Status'?: LookupFilterStatusFilter;
    /**
     * 
     * @type {LookupFilterTextSearch}
     * @memberof RestLookupFilter
     */
    'Text'?: LookupFilterTextSearch;
    /**
     * 
     * @type {TreeNodeType}
     * @memberof RestLookupFilter
     */
    'Type'?: TreeNodeType;
}



