/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RestError
 */
export interface RestError {
    /**
     * 
     * @type {string}
     * @memberof RestError
     */
    'Code'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestError
     */
    'Detail'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RestError
     */
    'Meta'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof RestError
     */
    'Source'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestError
     */
    'Title'?: string;
}

