/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestNamespaceValuesResponse
 */
export interface RestNamespaceValuesResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof RestNamespaceValuesResponse
     */
    values?: Array<string>;
}

/**
 * Check if a given object implements the RestNamespaceValuesResponse interface.
 */
export function instanceOfRestNamespaceValuesResponse(value: object): value is RestNamespaceValuesResponse {
    return true;
}

export function RestNamespaceValuesResponseFromJSON(json: any): RestNamespaceValuesResponse {
    return RestNamespaceValuesResponseFromJSONTyped(json, false);
}

export function RestNamespaceValuesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestNamespaceValuesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'values': json['Values'] == null ? undefined : json['Values'],
    };
}

export function RestNamespaceValuesResponseToJSON(json: any): RestNamespaceValuesResponse {
    return RestNamespaceValuesResponseToJSONTyped(json, false);
}

export function RestNamespaceValuesResponseToJSONTyped(value?: RestNamespaceValuesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Values': value['values'],
    };
}

