/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RestUserMeta } from './RestUserMeta';
import {
    RestUserMetaFromJSON,
    RestUserMetaFromJSONTyped,
    RestUserMetaToJSON,
    RestUserMetaToJSONTyped,
} from './RestUserMeta';

/**
 * 
 * @export
 * @interface RestUserMetaList
 */
export interface RestUserMetaList {
    /**
     * 
     * @type {Array<RestUserMeta>}
     * @memberof RestUserMetaList
     */
    userMeta?: Array<RestUserMeta>;
}

/**
 * Check if a given object implements the RestUserMetaList interface.
 */
export function instanceOfRestUserMetaList(value: object): value is RestUserMetaList {
    return true;
}

export function RestUserMetaListFromJSON(json: any): RestUserMetaList {
    return RestUserMetaListFromJSONTyped(json, false);
}

export function RestUserMetaListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestUserMetaList {
    if (json == null) {
        return json;
    }
    return {
        
        'userMeta': json['UserMeta'] == null ? undefined : ((json['UserMeta'] as Array<any>).map(RestUserMetaFromJSON)),
    };
}

export function RestUserMetaListToJSON(json: any): RestUserMetaList {
    return RestUserMetaListToJSONTyped(json, false);
}

export function RestUserMetaListToJSONTyped(value?: RestUserMetaList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UserMeta': value['userMeta'] == null ? undefined : ((value['userMeta'] as Array<any>).map(RestUserMetaToJSON)),
    };
}

