/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActivityObject } from './activity-object';
// May contain unused imports in some cases
// @ts-ignore
import type { ActivitySubscription } from './activity-subscription';
// May contain unused imports in some cases
// @ts-ignore
import type { RestContextWorkspace } from './rest-context-workspace';
// May contain unused imports in some cases
// @ts-ignore
import type { RestCountMeta } from './rest-count-meta';
// May contain unused imports in some cases
// @ts-ignore
import type { RestDataSourceFeatures } from './rest-data-source-features';
// May contain unused imports in some cases
// @ts-ignore
import type { RestFilePreview } from './rest-file-preview';
// May contain unused imports in some cases
// @ts-ignore
import type { RestImageMeta } from './rest-image-meta';
// May contain unused imports in some cases
// @ts-ignore
import type { RestJsonMeta } from './rest-json-meta';
// May contain unused imports in some cases
// @ts-ignore
import type { RestLockInfo } from './rest-lock-info';
// May contain unused imports in some cases
// @ts-ignore
import type { RestMode } from './rest-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { RestRevisionMeta } from './rest-revision-meta';
// May contain unused imports in some cases
// @ts-ignore
import type { RestShareLink } from './rest-share-link';
// May contain unused imports in some cases
// @ts-ignore
import type { RestUserMeta } from './rest-user-meta';
// May contain unused imports in some cases
// @ts-ignore
import type { TreeNodeType } from './tree-node-type';

/**
 * Representation of a file or folder
 * @export
 * @interface RestNode
 */
export interface RestNode {
    /**
     * 
     * @type {Array<ActivityObject>}
     * @memberof RestNode
     */
    'Activities'?: Array<ActivityObject>;
    /**
     * 
     * @type {RestLockInfo}
     * @memberof RestNode
     */
    'ContentLock'?: RestLockInfo;
    /**
     * 
     * @type {string}
     * @memberof RestNode
     */
    'ContentType'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestNode
     */
    'ContentsHash'?: string;
    /**
     * 
     * @type {RestContextWorkspace}
     * @memberof RestNode
     */
    'ContextWorkspace'?: RestContextWorkspace;
    /**
     * 
     * @type {RestDataSourceFeatures}
     * @memberof RestNode
     */
    'DataSourceFeatures'?: RestDataSourceFeatures;
    /**
     * 
     * @type {Array<RestCountMeta>}
     * @memberof RestNode
     */
    'FolderMeta'?: Array<RestCountMeta>;
    /**
     * 
     * @type {string}
     * @memberof RestNode
     */
    'HashingMethod'?: string;
    /**
     * 
     * @type {RestImageMeta}
     * @memberof RestNode
     */
    'ImageMeta'?: RestImageMeta;
    /**
     * 
     * @type {boolean}
     * @memberof RestNode
     */
    'IsBookmarked'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RestNode
     */
    'IsRecycleBin'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RestNode
     */
    'IsRecycled'?: boolean;
    /**
     * 
     * @type {Array<RestJsonMeta>}
     * @memberof RestNode
     */
    'Metadata'?: Array<RestJsonMeta>;
    /**
     * 
     * @type {RestMode}
     * @memberof RestNode
     */
    'Mode'?: RestMode;
    /**
     * Date instead of TS ?
     * @type {string}
     * @memberof RestNode
     */
    'Modified'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestNode
     */
    'Path': string;
    /**
     * 
     * @type {Array<RestFilePreview>}
     * @memberof RestNode
     */
    'Previews'?: Array<RestFilePreview>;
    /**
     * 
     * @type {RestRevisionMeta}
     * @memberof RestNode
     */
    'RevisionMeta'?: RestRevisionMeta;
    /**
     * 
     * @type {Array<RestShareLink>}
     * @memberof RestNode
     */
    'Shares'?: Array<RestShareLink>;
    /**
     * 
     * @type {string}
     * @memberof RestNode
     */
    'Size'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestNode
     */
    'StorageETag'?: string;
    /**
     * 
     * @type {Array<ActivitySubscription>}
     * @memberof RestNode
     */
    'Subscriptions'?: Array<ActivitySubscription>;
    /**
     * 
     * @type {TreeNodeType}
     * @memberof RestNode
     */
    'Type'?: TreeNodeType;
    /**
     * 
     * @type {Array<RestUserMeta>}
     * @memberof RestNode
     */
    'UserMetadata'?: Array<RestUserMeta>;
    /**
     * 
     * @type {string}
     * @memberof RestNode
     */
    'Uuid': string;
}



