/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestDataSourceFeatures
 */
export interface RestDataSourceFeatures {
    /**
     * 
     * @type {boolean}
     * @memberof RestDataSourceFeatures
     */
    encrypted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RestDataSourceFeatures
     */
    versioned?: boolean;
}

/**
 * Check if a given object implements the RestDataSourceFeatures interface.
 */
export function instanceOfRestDataSourceFeatures(value: object): value is RestDataSourceFeatures {
    return true;
}

export function RestDataSourceFeaturesFromJSON(json: any): RestDataSourceFeatures {
    return RestDataSourceFeaturesFromJSONTyped(json, false);
}

export function RestDataSourceFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestDataSourceFeatures {
    if (json == null) {
        return json;
    }
    return {
        
        'encrypted': json['Encrypted'] == null ? undefined : json['Encrypted'],
        'versioned': json['Versioned'] == null ? undefined : json['Versioned'],
    };
}

export function RestDataSourceFeaturesToJSON(json: any): RestDataSourceFeatures {
    return RestDataSourceFeaturesToJSONTyped(json, false);
}

export function RestDataSourceFeaturesToJSONTyped(value?: RestDataSourceFeatures | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Encrypted': value['encrypted'],
        'Versioned': value['versioned'],
    };
}

