/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceResourcePolicyPolicyEffect } from './ServiceResourcePolicyPolicyEffect';
import {
    ServiceResourcePolicyPolicyEffectFromJSON,
    ServiceResourcePolicyPolicyEffectFromJSONTyped,
    ServiceResourcePolicyPolicyEffectToJSON,
    ServiceResourcePolicyPolicyEffectToJSONTyped,
} from './ServiceResourcePolicyPolicyEffect';
import type { ServiceResourcePolicyAction } from './ServiceResourcePolicyAction';
import {
    ServiceResourcePolicyActionFromJSON,
    ServiceResourcePolicyActionFromJSONTyped,
    ServiceResourcePolicyActionToJSON,
    ServiceResourcePolicyActionToJSONTyped,
} from './ServiceResourcePolicyAction';

/**
 * 
 * @export
 * @interface ServiceResourcePolicy
 */
export interface ServiceResourcePolicy {
    /**
     * 
     * @type {ServiceResourcePolicyAction}
     * @memberof ServiceResourcePolicy
     */
    action?: ServiceResourcePolicyAction;
    /**
     * 
     * @type {ServiceResourcePolicyPolicyEffect}
     * @memberof ServiceResourcePolicy
     */
    effect?: ServiceResourcePolicyPolicyEffect;
    /**
     * 
     * @type {string}
     * @memberof ServiceResourcePolicy
     */
    jsonConditions?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResourcePolicy
     */
    resource?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResourcePolicy
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceResourcePolicy
     */
    id?: string;
}



/**
 * Check if a given object implements the ServiceResourcePolicy interface.
 */
export function instanceOfServiceResourcePolicy(value: object): value is ServiceResourcePolicy {
    return true;
}

export function ServiceResourcePolicyFromJSON(json: any): ServiceResourcePolicy {
    return ServiceResourcePolicyFromJSONTyped(json, false);
}

export function ServiceResourcePolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceResourcePolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['Action'] == null ? undefined : ServiceResourcePolicyActionFromJSON(json['Action']),
        'effect': json['Effect'] == null ? undefined : ServiceResourcePolicyPolicyEffectFromJSON(json['Effect']),
        'jsonConditions': json['JsonConditions'] == null ? undefined : json['JsonConditions'],
        'resource': json['Resource'] == null ? undefined : json['Resource'],
        'subject': json['Subject'] == null ? undefined : json['Subject'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ServiceResourcePolicyToJSON(json: any): ServiceResourcePolicy {
    return ServiceResourcePolicyToJSONTyped(json, false);
}

export function ServiceResourcePolicyToJSONTyped(value?: ServiceResourcePolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Action': ServiceResourcePolicyActionToJSON(value['action']),
        'Effect': ServiceResourcePolicyPolicyEffectToJSON(value['effect']),
        'JsonConditions': value['jsonConditions'],
        'Resource': value['resource'],
        'Subject': value['subject'],
        'id': value['id'],
    };
}

