/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceResourcePolicyAction } from './ServiceResourcePolicyAction';
import {
    ServiceResourcePolicyActionFromJSON,
    ServiceResourcePolicyActionFromJSONTyped,
    ServiceResourcePolicyActionToJSON,
    ServiceResourcePolicyActionToJSONTyped,
} from './ServiceResourcePolicyAction';

/**
 * 
 * @export
 * @interface ServiceResourcePolicyQuery
 */
export interface ServiceResourcePolicyQuery {
    /**
     * 
     * @type {ServiceResourcePolicyAction}
     * @memberof ServiceResourcePolicyQuery
     */
    action?: ServiceResourcePolicyAction;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceResourcePolicyQuery
     */
    any?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceResourcePolicyQuery
     */
    empty?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ServiceResourcePolicyQuery
     */
    leftIdentifier?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ServiceResourcePolicyQuery
     */
    subjects?: Array<string>;
}



/**
 * Check if a given object implements the ServiceResourcePolicyQuery interface.
 */
export function instanceOfServiceResourcePolicyQuery(value: object): value is ServiceResourcePolicyQuery {
    return true;
}

export function ServiceResourcePolicyQueryFromJSON(json: any): ServiceResourcePolicyQuery {
    return ServiceResourcePolicyQueryFromJSONTyped(json, false);
}

export function ServiceResourcePolicyQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceResourcePolicyQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['Action'] == null ? undefined : ServiceResourcePolicyActionFromJSON(json['Action']),
        'any': json['Any'] == null ? undefined : json['Any'],
        'empty': json['Empty'] == null ? undefined : json['Empty'],
        'leftIdentifier': json['LeftIdentifier'] == null ? undefined : json['LeftIdentifier'],
        'subjects': json['Subjects'] == null ? undefined : json['Subjects'],
    };
}

export function ServiceResourcePolicyQueryToJSON(json: any): ServiceResourcePolicyQuery {
    return ServiceResourcePolicyQueryToJSONTyped(json, false);
}

export function ServiceResourcePolicyQueryToJSONTyped(value?: ServiceResourcePolicyQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Action': ServiceResourcePolicyActionToJSON(value['action']),
        'Any': value['any'],
        'Empty': value['empty'],
        'LeftIdentifier': value['leftIdentifier'],
        'Subjects': value['subjects'],
    };
}

