/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TreeWorkspaceRelativePath
 */
export interface TreeWorkspaceRelativePath {
    /**
     * 
     * @type {string}
     * @memberof TreeWorkspaceRelativePath
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeWorkspaceRelativePath
     */
    wsLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeWorkspaceRelativePath
     */
    wsScope?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeWorkspaceRelativePath
     */
    wsSlug?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeWorkspaceRelativePath
     */
    wsUuid?: string;
}

/**
 * Check if a given object implements the TreeWorkspaceRelativePath interface.
 */
export function instanceOfTreeWorkspaceRelativePath(value: object): value is TreeWorkspaceRelativePath {
    return true;
}

export function TreeWorkspaceRelativePathFromJSON(json: any): TreeWorkspaceRelativePath {
    return TreeWorkspaceRelativePathFromJSONTyped(json, false);
}

export function TreeWorkspaceRelativePathFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeWorkspaceRelativePath {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['Path'] == null ? undefined : json['Path'],
        'wsLabel': json['WsLabel'] == null ? undefined : json['WsLabel'],
        'wsScope': json['WsScope'] == null ? undefined : json['WsScope'],
        'wsSlug': json['WsSlug'] == null ? undefined : json['WsSlug'],
        'wsUuid': json['WsUuid'] == null ? undefined : json['WsUuid'],
    };
}

export function TreeWorkspaceRelativePathToJSON(json: any): TreeWorkspaceRelativePath {
    return TreeWorkspaceRelativePathToJSONTyped(json, false);
}

export function TreeWorkspaceRelativePathToJSONTyped(value?: TreeWorkspaceRelativePath | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Path': value['path'],
        'WsLabel': value['wsLabel'],
        'WsScope': value['wsScope'],
        'WsSlug': value['wsSlug'],
        'WsUuid': value['wsUuid'],
    };
}

