/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const TreeNodeChangeEventEventType = {
    Create: 'CREATE',
    Read: 'READ',
    UpdatePath: 'UPDATE_PATH',
    UpdateContent: 'UPDATE_CONTENT',
    UpdateMeta: 'UPDATE_META',
    UpdateUserMeta: 'UPDATE_USER_META',
    Delete: 'DELETE'
} as const;

export type TreeNodeChangeEventEventType = typeof TreeNodeChangeEventEventType[keyof typeof TreeNodeChangeEventEventType];



