/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TreeNodeType = {
    Unknown: 'UNKNOWN',
    Leaf: 'LEAF',
    Collection: 'COLLECTION'
} as const;
export type TreeNodeType = typeof TreeNodeType[keyof typeof TreeNodeType];


export function instanceOfTreeNodeType(value: any): boolean {
    for (const key in TreeNodeType) {
        if (Object.prototype.hasOwnProperty.call(TreeNodeType, key)) {
            if (TreeNodeType[key as keyof typeof TreeNodeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TreeNodeTypeFromJSON(json: any): TreeNodeType {
    return TreeNodeTypeFromJSONTyped(json, false);
}

export function TreeNodeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeNodeType {
    return json as TreeNodeType;
}

export function TreeNodeTypeToJSON(value?: TreeNodeType | null): any {
    return value as any;
}

export function TreeNodeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): TreeNodeType {
    return value as TreeNodeType;
}

