/* tslint:disable */
/* eslint-disable */
/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TreeGeoQuery } from './tree-geo-query';
// May contain unused imports in some cases
// @ts-ignore
import type { TreeNodeType } from './tree-node-type';

/**
 * 
 * @export
 * @interface TreeQuery
 */
export interface TreeQuery {
    /**
     * 
     * @type {string}
     * @memberof TreeQuery
     */
    'Content'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeQuery
     */
    'DurationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeQuery
     */
    'ETag'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TreeQuery
     */
    'ExcludedPathPrefix'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TreeQuery
     */
    'Extension'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeQuery
     */
    'FileName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeQuery
     */
    'FileNameOrContent'?: string;
    /**
     * Bleve-like search query to search for a specific metadata value. When querying nodes, this will redirect this query to the Search Engine. When filtering an input, this will load an in-memory bleve engine to evaluate the node.  Bleve query string format is a space separated list of `[+-]key:value`, where node meta keys must be prepended with \"Meta.\" For Example, for tags: `+Meta.usermeta-tags:myvalue`
     * @type {string}
     * @memberof TreeQuery
     */
    'FreeString'?: string;
    /**
     * 
     * @type {TreeGeoQuery}
     * @memberof TreeQuery
     */
    'GeoQuery'?: TreeGeoQuery;
    /**
     * 
     * @type {string}
     * @memberof TreeQuery
     */
    'MaxDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeQuery
     */
    'MaxSize'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeQuery
     */
    'MinDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TreeQuery
     */
    'MinSize'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TreeQuery
     */
    'Not'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TreeQuery
     */
    'PathDepth'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof TreeQuery
     */
    'PathPrefix'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TreeQuery
     */
    'Paths'?: Array<string>;
    /**
     * 
     * @type {TreeNodeType}
     * @memberof TreeQuery
     */
    'Type'?: TreeNodeType;
    /**
     * 
     * @type {Array<string>}
     * @memberof TreeQuery
     */
    'UUIDs'?: Array<string>;
}



